### ISSUE TITLE
Haraka crashed.

### ISSUE THREAD

**Issue by MrSorcus** [haraka/Haraka#2304] opened 2017-11-29 14:35 UTC
### system info

Haraka | Haraka.js — Version: 2.8.16
 --- | :--- 
Node | v6.11.3
OS | Linux server.inwebse.org 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.2k-fips  26 Jan 2017

Logs (last 100 lines) - https://gist.github.com/MrSorcus/4214a559895f1165e1fd2e254cfefd6a

**Comment by MrSorcus** [comment] 2017-12-01 14:25
Maybe something with systemd unit?
```
[Unit]
Description = Haraka MTA
After = syslog.target network.target remote-fs.target nss-lookup.target

[Service]
Type = forking
ExecStart = /usr/bin/haraka -c /etc/haraka
PIDFile = /var/run/haraka.pid
KillMode = process
PrivateTmp = true

[Install]
WantedBy = multi-user.target
```

**Comment by MrSorcus** [comment] 2017-12-01 14:37
Crashed again
```
2017-11-30T23:30:44.305Z [CRIT] [-] [core] Error: We are already running hooks! Fatal error!
2017-11-30T23:30:44.305Z [CRIT] [-] [core]     at Object.plugins.run_hooks (/usr/lib/node_modules/Haraka/plugins.js:403:15)
2017-11-30T23:30:44.305Z [CRIT] [-] [core]     at Connection.process_line (/usr/lib/node_modules/Haraka/connection.js:369:21)
2017-11-30T23:30:44.305Z [CRIT] [-] [core]     at Connection._process_data (/usr/lib/node_modules/Haraka/connection.js:493:18)
2017-11-30T23:30:44.305Z [CRIT] [-] [core]     at Connection.process_data (/usr/lib/node_modules/Haraka/connection.js:404:10)
2017-11-30T23:30:44.305Z [CRIT] [-] [core]     at pluggableStream.<anonymous> (/usr/lib/node_modules/Haraka/connection.js:136:14)
2017-11-30T23:30:44.305Z [CRIT] [-] [core]     at emitOne (events.js:96:13)
2017-11-30T23:30:44.306Z [CRIT] [-] [core]     at pluggableStream.emit (events.js:188:7)
2017-11-30T23:30:44.306Z [CRIT] [-] [core]     at TLSSocket.<anonymous> (/usr/lib/node_modules/Haraka/tls_socket.js:57:14)
2017-11-30T23:30:44.306Z [CRIT] [-] [core]     at emitOne (events.js:96:13)
2017-11-30T23:30:44.306Z [CRIT] [-] [core]     at TLSSocket.emit (events.js:188:7)
2017-11-30T23:30:44.362Z [NOTICE] [-] [core] Shutting down
```

**Comment by baudehlo** [comment] 2017-12-01 15:05
Duplicate of #1576, #2202 and #2222

**Closed** 2017-12-08 05:48 UTC
