### ISSUE TITLE
Support for environment variables in config files

### ISSUE THREAD

**Issue by adelphes** [haraka/Haraka#2098] opened 2017-09-11 10:35 UTC
I've seen that this has come up a couple of times and dismissed with "not supported" or "use symlinks", but this would really be useful for creating different test & runtime configurations of Haraka. The use of environment variables in config files is also widely implemented in other software.

I think that adding support for expanding `$XYZ` or `${X Y Z}` when reading configuration values wouldn't be too much work (feel free to tell me I'm wrong) and would provide a huge level of flexibility to Haraka without requiring the user to manually code symlinks to files/folders.

Related: #32, #1516

**Comment by KingNoosh** [comment] 2017-09-11 10:46
The main reason why the push in config files is to pull users from qpsmtpd, I don't THINK it'll be difficult but I'll need to make it compatible with other ways.

All the current config files with extensions will look for ini, json and yaml. I could have it look for environmental variables prefixing with haraka seperating with maybe a dot.

I can probably draft this whenever I get time after work.

**Comment by smfreegard** [comment] 2017-09-11 11:07
> The main reason why the push in config files is to pull users from qpsmtpd

No - it's because we've had people asking for things like #32 e.g. NODE_ENV=dev/prod which would require something unusual and not just adding support for environment variables.  e.g. it would require checking of the environment variable and then supplying individual values for 'prod', 'dev' and a default value or somesuch.   So actually having a 'prod' and 'dev' config directories is therefore a simpler approach.

Adding environment variables would probably be quite easy, the only part that might be tricky is handling all of the different formats e.g. JSON, YAML etc. that Haraka config allows to use as $foo will probably need to be escaped in some way, however to handle the #32 case is probably quite difficult.   Additionally there are multiple files where it wouldn't make sense e.g. config/plugins on config/host_list etc.

So the actual reason we've never added this before is simply because the core devs simply haven't had a use for this and could see multiple alternative ways to handle these cases.

If someone wants to have a go at designing how this should work - we should probably have a discussion about it here beforehand so we can evaluate the design etc.

**Comment by msimerson** [comment] 2017-09-11 16:53
We already have [some basic elements of ENV use](https://github.com/haraka/haraka-config/blob/master/configfile.js) in [haraka-config](https://github.com/haraka/haraka-config). It's used in some tests to choose `test/config` as the config directory instead of `./config`. In other places we use this instead:

```js
this.plugin.config = this.plugin.config.module_config(path.resolve('test'));
```

**Comment by KingNoosh** [comment] 2017-09-19 14:22
A clarification on this ticket is that @adelphes means that we'd like the ability to set config values via environmental variables.

Not load specific configs in specific node environments.

**Comment by msimerson** [comment] 2018-12-07 07:45
Duplicate of haraka/haraka-config#39

**Closed by msimerson** 2018-12-07 07:45 UTC
Labels: Discuss, Feature Request, Idea
