### ISSUE TITLE
Remove or rework graceful shutdown code

### ISSUE THREAD

**Issue by baudehlo** [haraka/Haraka#2024] opened 2017-07-28 13:38 UTC
The graceful shutdown code has proved fragile and annoying.

I still think it's the right thing to do in most cases, but that's a hard sell for a feature that isn't working well.

This ticket is here to discuss the options.

**Comment by msimerson** [comment] 2017-07-28 16:05
Collation of graceful Issue & PR activity:

- 2014-06-11 -  #603 - feature request: graceful restart
- 2016-06-02 - #1470 - graceful shutdown and restart
- 2016=06-07 - #1503 - more graceful shutdown
- 2016-10-06 - #1639 - Tidy-up graceful shutdown and fix for non-cluster mode
- 2017-05-19 - #1926 - cluster shutdown/restart issues
    - has discussion about usefulness of graceful
- 2017-05-21 - #1927 - graceful shutdown off by default
- 2017-05-22 - #1933 - graceful restart doesn't work with cluster on
- 2017-05-23 - #1936 - crash in master if socket times out
    - #1937 - Check pool exists before delete

In #1926 @baudehlo saith, "I'm also considering killing the graceful code completely" and @smfreegard  & @msimerson piled on the death-to-graceful party.

I still like the idea of graceful but I loathe the implementation and the side effects. When I tell Haraka to shut down, I want it to behave like most typical daemons and shut down NOW. Notable exceptions include haproxy which will wait for HTTP connections to close before exiting, which is normally fine because HTTP is stateless. It becomes much less fine when WebSockets are involved.

With Haraka, SMTP sessions are [sometimes much] longer lasting and we don't want to be waiting 10s of seconds or minutes for Haraka to shut down.

Also, the current code treats all plugins the same. So `haraka-plugin-redis` (and other DBish plugins) get the shutdown signal and drop their DB connections out from under other plugins that are still using them. Now the pending current connections have all manner of subterfuge that prevents them from continuing normally. This isn't the only graceful issue, it's just the one that happens to annoy me the most.

Dependency ordering is a difficult business. It took decades for SYS 5 init / rc.d to get it mostly right and now the linux community is having its salad days making sure their dependencies are declared and working properly for systemd. I don't think we have the resources (specifically: time) to invest in getting graceful to work well within Haraka. Thus, I vote to nuke it.

**Comment by msimerson** [comment] 2017-07-28 16:12
I might have to amend my "annoys me the most" comment, as the unpredictably surfacing test failures have also been quite the thorn in the side.

**Comment by smfreegard** [comment] 2017-07-28 16:34
> Also, the current code treats all plugins the same. So haraka-plugin-redis (and other DBish plugins) get the shutdown signal and drop their DB connections out from under other plugins that are still using them. 

This is a very good point and something that I hadn't really considered as I'm intentionally not using a newer Haraka to avoid the outbound, shutdown issues and issues in my plugins caused by some of the extensive refactoring and code changes that came later.

As you point out, this is going to be complicated to do and would involve not running the shutdown code until all the clients have disconnected, which means we would have to track each connection per-child and in the disconnect hook run the shutdown code for that child when the last connection completes, to ensure that everything necessary is still running.

IMO - The 'ideal' way for this to work is to close the listeners and immediately fork a new master process. leaving the 'old' master to exit once all of the connections are finished.  That would then seem almost 'instantaneous' to the end-user.

However - that approach is difficult due to the service managers (e.g. systemd, runit, init) as they'll be 'watching' the current master process that we're trying to shutdown instead of the 'new' master that we're starting up.

The only way I can think of to do this transparently would be to make a new 'parent' process in Haraka which only forks the master and workers and then listens for signals.   That way it could spawn a new master once the old master has stopped the listeners, so you'd get a near instant restart and the old connections would close gracefully.

That said - what's the point of doing any of this graceful stuff anyway being as SMTP is designed with this in mind, so if you drop a connection halfway through, it will be retried later anyway???

**Comment by msimerson** [comment] 2017-07-28 16:47
Exactly. If it were HUMANS on the other end of the SMTP conversation, I'd be much more inclined to humor the learning curve and effort to make graceful work well. But a HUP signal means "wipe quickly and get off the pot because we're flushing your resources pronto!"

**Comment by baudehlo** [comment] 2017-07-28 17:44
One thing I can propose is instead of ripping it all out completely, that we keep the --graceful option only. i.e. a normal shutdown is just a process.exit(), but we keep the option to try and reload gracefully.

**Comment by msimerson** [comment] 2017-07-28 17:47
>  keep the --graceful option 

So long as we put some thar-be-dragons comments around the entry points of that code that points users at this issue, I'm fine with that too.

**Comment by msimerson** [comment] 2017-08-22 20:42
It seems the discussion has concluded. I think @baudehlo should make a decision or close the issue.

**Comment by baudehlo** [comment] 2017-08-23 00:24
Give me a bit. Got a baby to deal with.

**Closed** 2017-09-02 23:14 UTC
Labels: Discuss

**Comment by msimerson** [comment] 2017-09-02 23:18
> Give me a bit. Got a baby to deal with.

Let's put this issue to bed for now? The pain points have been addressed already. If we want to nuke graceful in the future, PR #2025 can be resurrected. If we opt to address the issues and improve the graceful code, that'll be it's own PR, when someone has the time and energy to tackle it. Fair enough?

**Comment by baudehlo** [comment] 2017-09-03 01:32
I'm lost as to what the resolution is. If it's to keep the graceful option but not use it for shutdown, totally cool with that.

**Comment by msimerson** [comment] 2017-09-03 02:50
Yep, that's what we've done.
