### ISSUE TITLE
Can I use Haraka Outbound Spam gateway for broadband users of ISP

### ISSUE THREAD

**Issue by thusharamanoj** [haraka/Haraka#2954] opened 2021-06-29 08:03 UTC
**Describe the solution you'd like**
For ISP, broadband customers are sending emails via port 25. can I use Haraka outbound spam gateway to throttle connections ? my main idea is to stop IP blacklisting global RBL sites. 

**Describe alternatives you've considered**
now we are using cybonet outbound spam gateway
https://www.cybonet.com/en/products/outbound-spam-guard

I want to implement similar outbound spam gateway by using Haraka . is it posible ?

**Comment by baudehlo** [comment] 2021-06-29 14:02
It's totally possible, but bear in mind that Haraka is not usually a complete solution, and will _likely_ require some custom coding to achieve all this. Closing because it's not a bug.

**Closed by baudehlo** 2021-06-29 14:02 UTC
