### ISSUE TITLE
Haraka 2.8.17 install fails on CentOS 7 with Node v8

### ISSUE THREAD

**Issue by lnedry** [haraka/Haraka#2345] opened 2018-02-18 19:23 UTC
### system info

Haraka | Haraka.js — Version: 2.8.17
 --- | :--- 
Node | v8.9.4
OS | Linux haraka 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.2k-fips  26 Jan 2017

### Expected behavior

Install without errors.

### Observed behavior

```
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/8.9.4"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/Haraka/node_modules/dtrace-provider/.node-gyp"
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/lib/node_modules/Haraka/node_modules/dtrace-provider/.node-gyp/8.9.4"
```

The last two lines will repeat endlessly.

### Steps to reproduce

- install on 4GB Digital Ocean slice (CentOS 7.4 x64)
```
yum -y install gcc gcc-c++ make
curl --silent --location https://rpm.nodesource.com/setup_8.x | sudo bash -
yum -y install nodejs
npm install -g Haraka
```

**Comment by luto** [comment] 2018-02-19 23:08
I can confirm this with nodejs 8.9.4 on CentOS 7.4. This issue seems to be not with haraka directly, but with [node-dtrace-provider](https://github.com/chrisa/node-dtrace-provider), which is a dependency of bunyan, which is a dependency of ldapjs, which is a dependency of haraka-plugin-auth-ldap, which is an optional dependency of haraka. yay.

@lnedry as [described in an issue over there](https://github.com/chrisa/node-dtrace-provider/issues/110#issuecomment-357108324) running npm with `V=1` prevents it from dropping the permissions during build, which "fixes" this error. At least it does for me.

**Comment by luto** [comment] 2018-02-20 15:44
Correction: `V=1` does not resolve this issue for me, so there is still no way to install Haraka globally on CentOS 7.

**Comment by lnedry** [comment] 2018-02-20 15:49
I see a similar issue with Ubuntu 16.04.3.

**Comment by luto** [comment] 2018-02-20 21:05
@lnedry the same behavior is also shown with the `iconv` module, which led me to believe we're on the wrong path here. This is a general thing with node-gyp: https://github.com/nodejs/node-gyp/issues/454

**Comment by msimerson** [comment] 2018-03-01 19:12
The general issue is that NPM decided to wade into the file permissions pond with strong opinions and a half-baked implementation. It's caused no end of problems for many many users. I  [work around the NPM brain damage](https://github.com/msimerson/Mail-Toaster-6/blob/master/provision-haraka.sh#L25-L26) by globally setting `unsafe-perm true` and `user 0`.

**Comment by baudehlo** [comment] 2018-03-01 19:17
Does npm 5.7.1 fix this? (just released)

**Comment by msimerson** [comment] 2018-03-02 01:01
Doubtful, this bug is **way** older than the file permissions bug/patch that 5.7.1 "fixes."

**Comment by msimerson** [comment] 2018-09-04 18:33
Closing, this is a NPM issue outside the scope of Haraka. Use the workarounds suggested or linked to in this issue.

**Closed by msimerson** 2018-09-04 18:33 UTC

**Comment by timraybould** [comment] 2019-01-21 23:34
Is it currently possibly to install Haraka globally on a linux machine? I've installed it without the -g flag but that doesn't do much good.

@msimerson, maybe the answer is in your workaround? This is a required step I take it? Mind explaining a bit about how to adjust those settings?

**Comment by timraybould** [comment] 2019-01-21 23:40
Ah never mind, I didn't catch the git clone instructions. That worked.

**Comment by timraybould** [comment] 2019-01-21 23:52
Actually, it did not. Seemed to all install ok. But still getting `haraka: command not found`

**Comment by msimerson** [comment] 2019-01-22 05:18
@timraybould, show us what you did and what resulted. Without that we can't even try to help you.
