### ISSUE TITLE
LMTP plugin config not used

### ISSUE THREAD

**Issue by bmonty** [haraka/Haraka#1911] opened 2017-05-08 11:27 UTC
### system info

Haraka | Haraka.js — Version: 2.8.13
Node | v6.9.2
OS | Linux cd3b52dd3ad8 4.9.21-moby #1 SMP Wed Apr 12 01:18:47 UTC 2017 x86_64 Linux

### Expected behavior

The LMTP plugin should use the host and port values configured in `lmtp.ini`.

### Observed behavior

The LMTP plugin uses the default values in `lmtp.js` of `127.0.0.1` for host and `24` for port.

### Steps to reproduce

1. Create a `lmtp.ini` file in the config folder
```
host=172.17.0.3
port=6000
```
2. Attempt to deliver a message.
2. Haraka attempts to send the message to 127.0.0.1:24 instead of 172.17.0.3:6000.
```
[INFO] [D320CCE0-2E1E-43BB-AEA6-5E4ACCB026DE.1.1] [outbound] hook=get_mx plugin=queue/lmtp function=hook_get_mx params="test.local" retval=OK msg="[object Object]"
[INFO] [D320CCE0-2E1E-43BB-AEA6-5E4ACCB026DE.1.1] [outbound] Attempting to deliver to: 127.0.0.1:24 using LMTP (0) (0)
[INFO] [-] [core] [outbound] [outbound::24:127.0.0.1:undefined:50] dispense() clients=1 available=0
[ERROR] [-] [core] [outbound] Failed to get pool entry: Outbound connection error: Error: connect ECONNREFUSED 127.0.0.1:24
[INFO] [D320CCE0-2E1E-43BB-AEA6-5E4ACCB026DE.1.1] [outbound] Temp failing 1494242183737_1_30_4142.cd3b52dd3ad8 for 128 seconds: Tried all MXs
[INFO] [-] [core] [outbound] [outbound::24:127.0.0.1:undefined:50] dispense() clients=0 available=0
[INFO] [D320CCE0-2E1E-43BB-AEA6-5E4ACCB026DE.1.1] [outbound] hook=get_mx plugin=queue/lmtp function=hook_get_mx params="test.local" retval=OK msg="[object Object]"
[INFO] [D320CCE0-2E1E-43BB-AEA6-5E4ACCB026DE.1.1] [outbound] Attempting to deliver to: 127.0.0.1:24 using LMTP (0) (0)
[INFO] [-] [core] [outbound] [outbound::24:127.0.0.1:undefined:50] dispense() clients=1 available=0
[ERROR] [-] [core] [outbound] Failed to get pool entry: Outbound connection error: Error: connect ECONNREFUSED 127.0.0.1:24
[INFO] [D320CCE0-2E1E-43BB-AEA6-5E4ACCB026DE.1.1] [outbound] Temp failing 1494242312681_2_30_4142.cd3b52dd3ad8 for 256 seconds: Tried all MXs
[INFO] [-] [core] [outbound] [outbound::24:127.0.0.1:undefined:50] dispense() clients=0 available=0
```
I edited `lmtp.js` so the default values were my configuration and the mail was delivered correctly via lmtp.  Deleting the default values in `lmtp.js` caused the following error:
```
CRIT] [C1732CE1-51A5-4DDA-A33C-ECB82F150234.1.1] [outbound] Plugin queue/lmtp failed: Error: "name" argument must be a string
    at query (dns.js:227:13)
    at Object.exports.resolve (dns.js:273:12)
    at HMailItem.try_deliver (/opt/haraka/node_modules/Haraka/outbound.js:1187:9)
    at HMailItem.found_mx (/opt/haraka/node_modules/Haraka/outbound.js:1135:14)
    at HMailItem.get_mx_respond (/opt/haraka/node_modules/Haraka/outbound.js:1004:25)
    at callback (/opt/haraka/node_modules/Haraka/plugins.js:478:35)
    at Plugin.exports.hook_get_mx (/opt/haraka/node_modules/Haraka/plugins/queue/lmtp.js:28:12)
    at Object.plugins.run_next_hook (/opt/haraka/node_modules/Haraka/plugins.js:505:28)
    at Object.plugins.run_hooks (/opt/haraka/node_modules/Haraka/plugins.js:421:13)
    at HMailItem.get_mx (/opt/haraka/node_modules/Haraka/outbound.js:981:13)
    at HMailItem.send_email_respond (/opt/haraka/node_modules/Haraka/outbound.js:974:14)
    at callback (/opt/haraka/node_modules/Haraka/plugins.js:478:35)
    at Object.plugins.run_next_hook (/opt/haraka/node_modules/Haraka/plugins.js:482:45)
    at Object.plugins.run_hooks (/opt/haraka/node_modules/Haraka/plugins.js:421:13)
    at HMailItem._send (/opt/haraka/node_modules/Haraka/outbound.js:961:13)
    at HMailItem.<anonymous> (/opt/haraka/node_modules/Haraka/outbound.js:953:47)
[ERROR] [C1732CE1-51A5-4DDA-A33C-ECB82F150234.1.1] [outbound] queue/lmtp plugin ran callback multiple times - ignoring subsequent calls
```

**Comment by Dexus** [comment] 2017-05-08 12:23
Can you please check if it works when you remove the second param 'ini' from the config loader?

https://github.com/haraka/Haraka/blob/master/plugins/queue/lmtp.js#L9

**Comment by bmonty** [comment] 2017-05-09 10:05
I tried this and there was no change.

**Comment by Dexus** [comment] 2017-05-09 10:17
How did you install haraka? From git or npm and then with own config folder?

Von meinem iPhone gesendet

**Comment by smfreegard** [comment] 2017-05-09 10:19
@bmonty - try this: https://gist.github.com/smfreegard/acf270ccf04aeb35c31ec347c7133d46

If it doesn't work - paste me the log output from as I've modified this to output what was found in the INI file as I can't really spot what is wrong with this.

**Comment by bmonty** [comment] 2017-05-09 10:23
@Dexes I put a `package.json` file in `/opt/haraka` and ran yarn to install everything (so Haraka is in `node_modules`).  I created a `config` folder and put all the files.  Haraka is started using yarn with the command line `node_modules/Haraka/bin/haraka -c .`

**Comment by bmonty** [comment] 2017-05-09 10:28
@smfreegard seems connection is not defined.  I was trying to log the section variable to console without success before I opened this issue.  I you can point me in the right direction to output that value, I'll keep troubleshooting.

```
[CRIT] [3AAC88BB-38C1-4949-AD1B-C7AD9E637633.1.1] [outbound] Plugin queue/lmtp failed: ReferenceError: connection is not defined
    at Plugin.exports.hook_get_mx (/opt/haraka/node_modules/Haraka/plugins/queue/lmtp.js:11:5)
    at Object.plugins.run_next_hook (/opt/haraka/node_modules/Haraka/plugins.js:505:28)
    at Object.plugins.run_hooks (/opt/haraka/node_modules/Haraka/plugins.js:421:13)
    at HMailItem.get_mx (/opt/haraka/node_modules/Haraka/outbound.js:981:13)
    at HMailItem.send_email_respond (/opt/haraka/node_modules/Haraka/outbound.js:974:14)
    at callback (/opt/haraka/node_modules/Haraka/plugins.js:478:35)
    at Object.plugins.run_next_hook (/opt/haraka/node_modules/Haraka/plugins.js:482:45)
    at Object.plugins.run_hooks (/opt/haraka/node_modules/Haraka/plugins.js:421:13)
    at HMailItem._send (/opt/haraka/node_modules/Haraka/outbound.js:961:13)
    at HMailItem.<anonymous> (/opt/haraka/node_modules/Haraka/outbound.js:953:47)
```

**Comment by smfreegard** [comment] 2017-05-09 11:07
@bmonty Doh! - outbound always catches me out.   I've updated the gist and corrected it.

**Comment by bmonty** [comment] 2017-05-10 10:56
@smfreegard I inserted the log statement and the output was `[INFO] [-] [queue/lmtp] {}`

I also went to config.js:32 and added a console.log after `full_path` is set and the result was `/opt/haraka/node_modules/Haraka/config/lmtp.ini` which is not the path where I have my config.  It should be `/opt/haraka/config'.

I'm looking to see what's different about how the lmtp plugin is loaded because all the other plugins I'm using (clamd, dnsbl, spamassassin) load their config correctly.

**Comment by bmonty** [comment] 2017-05-13 12:48
I'm finding this really hard to debug since the plugin is running in a vm.  Any tips on things I can do to?

**Comment by msimerson** [comment] 2017-05-13 17:32
> I'm finding this really hard to debug since the plugin is running in a vm. Any tips on things I can do?

If your solution included a PR that stripped `vm.*` out of Haraka, I'd +1 it in a second. On balance, the benefits of using the vm have been meager while the many wasted developer hours caused by it have been considerable. (This is my opinion. It does not necessarily represent the views of @haraka/core.) However, I think it's fair to say that support for `vm` is at historic lows. It's also likely to make Haraka considerably faster.

**Comment by baudehlo** [comment] 2017-05-23 23:18
@bmonty tips would be to just add a lot of log* calls (my preferred method).

Or even use node with a debugger attached. This is pretty easy to do - start it with `node debug /path/to/haraka/bin/haraka -c <path>` and it will dump a URL to connect to on the command line. Then you can add a breakpoint in the plugin once loaded.

**Comment by baudehlo** [comment] 2017-05-24 23:44
I really can't replicate this. I'm going to close it because your way of installing Haraka is super weird, and unsupported. Please follow the instructions in the README.md.

**Closed by baudehlo** 2017-05-24 23:44 UTC

**Comment by bmonty** [comment] 2017-05-26 15:01
I used the supported install per the README and it fixed my issue.

Also, if running Haraka in a docker container, Haraka can't successfully lookup the hostnames of linked containers.  In this case putting the hostname in the `lmtp.ini` file will not allow Haraka to correctly deliver incoming messages.  This is an issue with node DNS lookups and not a problem with Haraka.  The workaround I used is to create the lmtp config at container start and use the environment variables docker creates to get the correct IP address of my lmtp server.

**Comment by smfreegard** [comment] 2017-05-26 15:08
Glad you got it working.

> This is an issue with node DNS lookups and not a problem with Haraka.

Sort of - we make a conscious decision not to use dns.looukp() anywhere in Haraka as it requires use of the node threadpool to workaround the non-asyncness of gethostbyname() calls.   Because we do a *lot* of DNS lookups it would reduce performance, so we don't do it.

Obviously this means that dockers chosen method of using /etc/hosts to pass this data won't work, any you therefore have to use workarounds.

> The workaround I used is to create the lmtp config at container start and use the environment variables docker creates to get the correct IP address of my lmtp server.

Exactly the way to do it, alternatively you could use some sort of service discovery mechanism.   The possibilities are endless.
