### ISSUE TITLE
Invalid IP address causes Haraka to crash

### ISSUE THREAD

**Issue by lnedry** [haraka/Haraka#2865] opened 2020-11-24 12:38 UTC
### system info

Haraka | Haraka.js — Version: 2.8.25
 --- | :--- 
Node | v13.14.0
OS | Linux mx3.bluestreak.net 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.2k-fips  26 Jan 2017

### Observed behavior
Haraka crashes

```
Nov 24 07:08:40 mx3 haraka[24923]: [INFO] [E623781C-31A5-4F30-BF3F-1EE3DC01DCD5] [helo.checks] helo_host: smtp-timely-01.communitect.com, ips: 192.41.19.137,192.41.19.171,192.41.19.138,192.41.19.173,192.41.19.135,192.41.19.170,192.41.19.134,192.41.19.172,192.41.19.136,192.41.19.139,::192.41.19.173,::192.41.19.138,::192.41.19.139,::192.41.19.134,::192.41.19.135,::192.41.19.136,::192.41.19.137,::192.41.19.171,::192.41.19.170,::192.41.19.172, pass:match_re, bare_ip, dynamic, big_co(not), literal_mismatch, valid_hostname, rdns_match(org_dom), forward_dns, host_mismatch
Nov 24 07:08:40 mx3 haraka[24923]: [INFO] [E623781C-31A5-4F30-BF3F-1EE3DC01DCD5] [core]  hook=helo plugin=dnswl function=check_dnswl params=smtp-timely-01.communitect.com retval=OK msg=""
Nov 24 07:08:41 mx3 haraka[24923]: [CRIT] [-] [core] Error: ipaddr: the address has neither IPv6 nor IPv4 format
Nov 24 07:08:41 mx3 haraka[24923]: [CRIT] [-] [core]     at Object.ipaddr.parse (/usr/local/share/.config/yarn/global/node_modules/ipaddr.js/lib/ipaddr.js:632:13)
Nov 24 07:08:41 mx3 haraka[24923]: [CRIT] [-] [core]     at Object.exports.ipv6_bogus (/usr/local/share/.config/yarn/global/node_modules/haraka-net-utils/index.js:347:26)
Nov 24 07:08:41 mx3 haraka[24923]: [CRIT] [-] [core]     at /usr/local/share/.config/yarn/global/node_modules/Haraka/plugins/mail_from.is_resolvable.js:131:39
Nov 24 07:08:41 mx3 haraka[24923]: [CRIT] [-] [core]     at /usr/local/share/.config/yarn/global/node_modules/haraka-net-utils/index.js:328:7
Nov 24 07:08:41 mx3 haraka[24923]: [CRIT] [-] [core]     at /usr/local/share/.config/yarn/global/node_modules/async/dist/async.js:3888:9
Nov 24 07:08:41 mx3 haraka[24923]: [CRIT] [-] [core]     at /usr/local/share/.config/yarn/global/node_modules/async/dist/async.js:473:16
Nov 24 07:08:41 mx3 haraka[24923]: [CRIT] [-] [core]     at iteratorCallback (/usr/local/share/.config/yarn/global/node_modules/async/dist/async.js:1064:13)
Nov 24 07:08:41 mx3 haraka[24923]: [CRIT] [-] [core]     at /usr/local/share/.config/yarn/global/node_modules/async/dist/async.js:969:16
Nov 24 07:08:41 mx3 haraka[24923]: [CRIT] [-] [core]     at /usr/local/share/.config/yarn/global/node_modules/async/dist/async.js:3885:13
Nov 24 07:08:41 mx3 haraka[24923]: [CRIT] [-] [core]     at QueryReqWrap.callback (/usr/local/share/.config/yarn/global/node_modules/haraka-net-utils/index.js:320:11)
Nov 24 07:08:41 mx3 haraka[24923]: [NOTICE] [-] [core] Shutting down
```

**Comment by msimerson** [comment] 2020-12-16 19:01
duplicate of #2763 , already fixed in newer Haraka versions (which depend on newer haraka-net-utils)

**Closed by msimerson** 2020-12-16 19:01 UTC
