### ISSUE TITLE
Haraka crashes when connecting IP cannot be resolved

### ISSUE THREAD

**Issue by kdkayat** [haraka/Haraka#3048] opened 2022-04-19 10:16 UTC
When a host with an unresolvable IP connects Haraka crashes and restarts. From the log:

```
[NOTICE] [B7590F09-20C1-49B3-8764-9BE85056B814] [core] connect ip=212.70.149.72 port=9268 local_ip=xxx local_port=465
[CRIT] [-] [core] Error: getHostByAddr ENOTFOUND 212.70.149.72
[CRIT] [-] [core]     at QueryReqWrap.onresolve [as oncomplete] (node:internal/dns/promises:173:17)
[NOTICE] [-] [core] Shutting down
```

Error started happening after a recent OS upgrade, not sure if related.

Haraka version 2.8.28 from Git master (Sun Apr 17 23:14:53 2022 -0700)
npm 8.7.0
node v16.13.0
OS FreeBSD 13.0-RELEASE-p11 i386

**Comment by msimerson** [comment] 2022-04-21 03:44
What plugin(s) are running first in your `config/plugins` file?

**Comment by kdkayat** [comment] 2022-04-26 20:23
plugins contains (in this order):
```
process_title
syslog
geoip
fcrdns
dnsbl
helo.checks
tls
auth/auth_vpopmaild
mail_from.is_resolvable
spf
qmail-deliverable
bounce
headers
data.uribl
attachment
spamassassin
dkim_sign
queue/qmail-queue
limit
```

**Comment by kayrus** [comment] 2022-05-10 22:35
#3023 also crashes on DNS issue

**Comment by DoobleD** [comment] 2022-07-18 15:50
I see the same error (on 2.8.28 too) but for me Haraka doesn't shut down. The error is treated as an unhandled promise rejection warning:

```
(node:2365973) UnhandledPromiseRejectionWarning: Error: getHostByAddr ENOTFOUND 119.41.193.91
    at QueryReqWrap.onresolve [as oncomplete] (internal/dns/promises.js:172:17)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
```

I'm using node v14.19.3. Node has [deprecated](https://nodejs.org/api/deprecations.html#DEP0018) unhandled exceptions and in more recent version that exits the process. Could it be the reason @kdkayat is seeing a shutdown instead?

**Comment by nikolabrdaroski** [comment] 2022-07-19 17:12
I’ve disabled fcrdns plugin and it works without it. So the issue is in that plugin.

**Comment by msimerson** [comment] 2022-07-20 19:52
Thanks for the reports, I think I see the issue. The DNS for the connection isn't resolving, and Haraka is timing out the plugin before the fcrdns plugin's internal DNS resolution timer times out.

Try enabling the fcrdns plugin and setting `[main]timeout=29` in `config/fcrdns.ini`.  The default is 30 seconds. I think that'll solve the problem.

**Closed** 2022-07-21 00:55 UTC

**Comment by DoobleD** [comment] 2022-07-21 14:52
> Try enabling the fcrdns plugin and setting `[main]timeout=29` in `config/fcrdns.ini`. The default is 30 seconds. I think that'll solve the problem.

Thank you for providing a fix so quickly @msimerson! It resolves the fcrdns timeout issue for me. Unfortunately it doesn't fix the `ENOTFOUND` error, at least in my case.

**Comment by DoobleD** [comment] 2022-07-22 16:23
Interestingly I also had CRIT errors with the data.uribl plugin identical to the fcrdns one, and the same fix (`[main]timeout=29` in `config/data.uribl.ini`) appears to resolve that issue as well.

`[CRIT] [195FF562-4411-4700-90A2-E505BB59CEBD] [core] Plugin data.uribl timed out on hook lookup_rdns - make sure it calls the callback
`

**Comment by msimerson** [comment] 2022-07-23 19:07
Hi @DoobleD, I think I have a fix for URIBL. If you could, install the newer version of the [plugin](https://raw.githubusercontent.com/msimerson/Haraka/uribl-overhaul/plugins/data.uribl.js) and test, that'd be great. There's an explanation of the issue in PR #3077.

**Comment by DoobleD** [comment] 2022-07-23 21:00
> Hi @DoobleD, I think I have a fix for URIBL. If you could, install the newer version of the [plugin](https://raw.githubusercontent.com/msimerson/Haraka/uribl-overhaul/plugins/data.uribl.js) and test, that'd be great. There's an explanation of the issue in PR #3077.

Thanks @msimerson! I'm testing it right now, I'll give it a few days to be sure and let you know.

**Comment by DoobleD** [comment] 2022-07-25 17:00
Great news @msimerson, with that additional fix both the data.uribl CRIT and the ENOTFOUND exception are gone. Thank you for your work!
