### ISSUE TITLE
smtp_forward and proxy have `enable_outbound` as default true

### ISSUE THREAD

**Issue by baudehlo** [haraka/Haraka#1472] opened 2016-05-19 23:21 UTC
### Haraka version

2.8.3
### Expected behavior

smtp_forward and proxy shouldn't be used for outbound by default.
### Observed behavior

They are used for outbound by default.
### Steps to reproduce

Just send an outbound mail with one of them enabled.

This is more a question for @smfreegard and @msimerson (who via git blame added the code, but I have no idea if it was there before that commit) so we can disable this behaviour by default - it's confusing when we have solid outbound mail support.

**Comment by msimerson** [comment] 2016-05-20 05:20
> smtp_forward and proxy shouldn't be used for outbound by default 

I disagree. If the plugins are enabled, then the most likely use case is that they will be the default outbound. The reason I use smtp_forward is specifically so that I do **not** queue messages for  domains I filter & forward for. I forward the connections to the destination MX (usually IP restricted Exchange) and if they reject, so do I. Any other way (besides training a couple Exchange admins to get AD/LDAP exposed to me for recipient validation) and I'll have tons of useless junk queued.

**Comment by baudehlo** [comment] 2016-05-20 14:01
Then it should be done via a get_mx hook via outbound, not this way.

That way outbound can split of multi-recipient-domains email to inbound and outbound, and deliver local mail to your inbound mail server.

**Comment by msimerson** [comment] 2016-05-21 18:22
> Then it should be done via a get_mx hook via outbound, not this way.

When outbound is used, queuing is involved. That's exactly what I don't want. I'll end up queueing garbage for invalid inbound recipients. The problem is that inbound is not granular enough to treat some inbound domains as *local* (accept & queue) and others as *remote* (smtp_forward only).

1. I accept inbound emails for domains that are not local (and smtp_forward to destination)
2. I accept inbound emails for domains that are local (and smtp_forward to local MX)
3. I accept [validated] outbound emails from domains that are local

In my case, the only time Haraka queues messages is in the third case. The rest of the time, Haraka is smtp_forwarding stuff based on blocks like this in smtp_forward.ini:

```ini
[example.com]
host=66.55.44.33
port=25
timeout=300
```

**Comment by baudehlo** [comment] 2016-05-25 00:22
So a better situation from my perspective would be:

* enable_outbound is disabled by default
* a get_mx hook is setup to send inbound email to the smtp_forward server
* future plans: if enable_outbound is set, allow the Address object on rcpt addresses to store a `local` value, and we do smtp_client stuff for those local addresses, and if it fails we can send a DENY/whatever, then if successful do `outbound.send_trans_email()` with the non-local addresses.

**Comment by msimerson** [comment] 2017-03-06 18:20
> allow the Address object on rcpt addresses to store a local value

Now we're talking.

One of the most confusing things about Haraka is that inbound and outbound are so poorly applicable to mail routing. Right now, inbound are connections w/o relaying and outbound are connections with relaying. That's good enough when a single recipient and single queue plugin are used. It gets hairy fast when more than one of either is used.

A common use case is Haraka as a filter host. Haraka accepts messages and forwards:

````
Internet -> Haraka -> user@local.com -> smtp_forward -> 😄 
Internet -> Haraka -> AUTH -> user@local.com -> outbound -> 😢 
````

Outbound fails to deliver because Haraka is the MX for local.com but Outbound doesn't know where to forward it! That's why the default is to have smtp_forward also queue for outbound. When using smtp_forward, Haraka is likely to be forwarding everything to a smart host(s) that handles the local vs remote distinction.

The breakdown is thinking of connections as inbound or outbound is too simplistic. Each recipient can have a different destination. If more than one recipient plugin is in use, the time during the connection when that routing information is known, and the optimal time to do something about it, is when a recipient plugin(s) vouches for the recipient.

- Tagging a recipient address with destination route seems like a sane approach.
- Outbound queueing can only reliably replace smtp_forward + smarthost when:
    - recipient plugins have `get_mx()` functions to inform Outbound of forward routes
    - or
    - recipient plugins tag each Address object with destination routes
- For inbound connections, when a forward route / plugin is detected and subsequent forward routes differ, deferring the subsequent recipients is the only solution that doesn't risk some recipients getting multiple deliveries.

Examples:
- QMD: I use multiple [domain.com] blocks in qmail-deliverable.ini and a default [main] block. If QMD vouches for a recipient, it knows which backend host claimed the address was deliverable and could tag that recipient Address with queue routing info.
- smtp_forward: I have a bunch of [example.com] forward routes defined in smtp_forward.ini. The new recipient validation added in #1847 could, at the time it vouches for a recipient, tag the recipient Address with the route info.

**Comment by baudehlo** [comment] 2017-03-06 18:26
Honestly having two separate subsystems for sending mail onwards
(smtp_client.js for smtp_forward and smtp_proxy) and outbound.js for
outbound mail is pretty confusing for everyone.

I guess the only valid reason you want it is so that failures don't result
in a bounce message. But once you have multiple destinations that is broken
anyway.

**Comment by msimerson** [comment] 2017-03-06 18:40
> But once you have multiple destinations that is broken anyway.

Unless you require the remote to split the transaction(s), as #1847 does. I should also point out that in my experience, the percentage of messages that have split transaction routing is very small (a low single digit percentage).

**Comment by baudehlo** [comment] 2017-03-06 20:37
From my reading, the only way #1847 "fixes" that is to do a CFV on the RCPT
TO. If you get a reject later in the SMTP stage it's still game over.

**Comment by msimerson** [comment] 2018-12-20 06:49
Since `transaction.notes.queue.wants` was added, I'm able to tag each transaction with the desired queue plugin. That resolves the issues above (for me) and I no longer object to setting enable_outbound=false as the default in the `queue/smtp_*` plugins.

**Comment by msimerson** [comment] 2019-01-04 22:07
Can someone think of a way to change the default behavior for new installs while preserving it for upgrades?  If not, I'm planning to tag and close this as a v3 issue and move it to the wiki TODO.

**Comment by baudehlo** [comment] 2019-01-07 18:42
A Big Warning Sign.

Which honestly is probably fine.

**Closed** 2019-01-18 20:02 UTC
