### ISSUE TITLE
Haraka throws exception because of machine name

### ISSUE THREAD

**Issue by leon-plutoflume** [haraka/Haraka#2342] opened 2018-02-16 10:50 UTC
### system info

Please report your OS, Node version, and Haraka version by running this shell script on your Haraka server and replacing this section with the output.

Haraka 2.8.15
Node v6.12.3
OS Linux 4.13.0-32-generic - 16.04.1-Ubuntu - _64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.2g

### Expected behavior

Haraka to not error because of machine name
### Observed behavior
My machine name had an underscore in it. When [qfile.parts](https://github.com/haraka/Haraka/blob/3732dda9e9a99067353a03002259fd952c67471f/outbound/qfile.js#L51) checks the transaction file name, which has the machine name appended to it, it throws a bad filename exception
### Steps to reproduce
Rename your machine to include an underscore

**Comment by KingNoosh** [comment] 2018-02-16 12:25
@leon-plutoflume is it possible you could give the log output too at some point?

Thanks

**Comment by msimerson** [comment] 2018-02-16 16:24
Duplicate of #2324 and already fixed in upcoming 2.8.17 release.

**Closed by msimerson** 2018-02-16 16:24 UTC
Labels: Bug

**Comment by qhxin** [comment] 2018-07-30 01:56
i think that the replace pattern should use /g expression maybe?
![image](https://user-images.githubusercontent.com/8831920/43373818-b9d7ce66-93de-11e8-9e96-1a8b3020b4dd.png)
