### ISSUE TITLE
Resets getting 503 response, causing bounce

### ISSUE THREAD

**Issue by dennisdupont** [haraka/Haraka#1852] opened 2017-03-11 06:57 UTC
### system info

Haraka | Haraka.js - Version: 2.8.13
 --- | :---
Node | v6.9.4
OS | Linux xxx.xxx.net 3.10.0-514.6.1.el7.x86_64 #1 SMP Wed Jan 18 13:06:36 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.1e-fips 11 Feb 2013

### Expected behavior
Not really sure what to expect, but I think this may be load related so perhaps Haraka should be executing a backoff/throttling algorithm? 

### Observed behavior
During periods of high volume we are experiencing a large number of "bounced" messages due to what seems to be a protocol interop problem between Haraka and Exchange (cloud version).

In the log below you can see a "C: DATA" followed by a "S: 250 2.0.0 Resetting" then we get a 5 second "timeout" and then a C: RSET followed by a "S: 503 5.5.2 Need mail command" which causes Haraka to go into bounce mode.

Perhaps the server has been resetting and is expecting Haraka to restart with the MAIL command.  Haraka seems to be ignoring the 250 following the data and is waiting for something else for 5 seconds.

Detailed logs for one example:
2017-03-10T16:20:17.425Z [DEBUG] [21FD02A6-1858-4D73-A6E9-959C7D59CCA1.28.1] [outbound] hook=get_mx plugin=relay function=force_routing params="xxx.com" retval=CONT msg=""
2017-03-10T16:20:17.425Z [DEBUG] [21FD02A6-1858-4D73-A6E9-959C7D59CCA1.28.1] [outbound] running get_mx hook in relay plugin
2017-03-10T16:20:17.425Z [DEBUG] [21FD02A6-1858-4D73-A6E9-959C7D59CCA1.28.1] [outbound] running get_mx hooks
2017-03-10T16:20:17.425Z [DEBUG] [21FD02A6-1858-4D73-A6E9-959C7D59CCA1.28.1] [outbound] running send_email hooks
2017-03-10T16:20:17.425Z [DEBUG] [21FD02A6-1858-4D73-A6E9-959C7D59CCA1.28.1] [outbound] Sending mail: 1489162817421_0_1709_757.xxx.net
2017-03-10T16:20:17.427Z [INFO] [21FD02A6-1858-4D73-A6E9-959C7D59CCA1.28.1] [outbound] Looking up A records for: xxx-com.mail.protection.outlook.com
2017-03-10T16:20:17.429Z [INFO] [21FD02A6-1858-4D73-A6E9-959C7D59CCA1.28.1] [outbound] Attempting to deliver to: 216.32.180.74:25 (0) (7)
2017-03-10T16:20:17.468Z [PROTOCOL] [21FD02A6-1858-4D73-A6E9-959C7D59CCA1.28.1] [outbound] C: MAIL FROM:<XXXXXX@xxx.com>
2017-03-10T16:20:17.482Z [PROTOCOL] [21FD02A6-1858-4D73-A6E9-959C7D59CCA1.28.1] [outbound] C: RCPT TO:<YYYYYY@xxx.com>
2017-03-10T16:20:17.482Z [PROTOCOL] [21FD02A6-1858-4D73-A6E9-959C7D59CCA1.28.1] [outbound] S: 250 2.1.0 Sender OK\r\n
2017-03-10T16:20:17.493Z [PROTOCOL] [21FD02A6-1858-4D73-A6E9-959C7D59CCA1.28.1] [outbound] C: DATA
2017-03-10T16:20:17.493Z [PROTOCOL] [21FD02A6-1858-4D73-A6E9-959C7D59CCA1.28.1] [outbound] S: 250 2.0.0 Resetting\r\n
2017-03-10T16:20:22.495Z [PROTOCOL] [21FD02A6-1858-4D73-A6E9-959C7D59CCA1.28.1] [outbound] C: RSET
2017-03-10T16:20:22.495Z [PROTOCOL] [21FD02A6-1858-4D73-A6E9-959C7D59CCA1.28.1] [outbound] S: 503 5.5.2 Need mail command\r\n
2017-03-10T16:20:22.496Z [DEBUG] [21FD02A6-1858-4D73-A6E9-959C7D59CCA1.28.1] [outbound] running bounce hooks
2017-03-10T16:20:22.496Z [INFO] [21FD02A6-1858-4D73-A6E9-959C7D59CCA1.28.1] [outbound] bouncing mail: 503 5.5.2 Need mail command

### Steps to reproduce
Send high volume mail to Exchange (which we do several times a week, so this is easily reproduced).

**Comment by webkp** [comment] 2017-04-19 07:44
We are testing Haraka as SMTP/Auth Proxy and it works great but with higher load we are experiencing the same problem.

2017-04-14T16:04:07.173Z [DEBUG] [059AD65E-B342-4EEB-A6D5-2588DBA6D485.1.11] [outbound] running send_email hooks
2017-04-14T16:04:07.173Z [DEBUG] [059AD65E-B342-4EEB-A6D5-2588DBA6D485.1.11] [outbound] Sending mail: 1492185847098_0_22981_5961.edg2.xxxxx.com
2017-04-14T16:04:07.173Z [DEBUG] [059AD65E-B342-4EEB-A6D5-2588DBA6D485.1.11] [outbound] running get_mx hooks
2017-04-14T16:04:07.173Z [DEBUG] [059AD65E-B342-4EEB-A6D5-2588DBA6D485.1.11] [outbound] running get_mx hook in queue/smtp_bridge plugin
2017-04-14T16:04:07.173Z [INFO] [059AD65E-B342-4EEB-A6D5-2588DBA6D485.1.11] [outbound] hook=get_mx plugin=queue/smtp_bridge function=hook_get_mx params="yyyyyy.com" retval=OK msg="[object Object]"
2017-04-14T16:04:07.173Z [DEBUG] [059AD65E-B342-4EEB-A6D5-2588DBA6D485.1.11] [outbound] Got an MX from Plugin: yyyyyy.com => 0 [object Object]
2017-04-14T16:04:07.173Z [INFO] [059AD65E-B342-4EEB-A6D5-2588DBA6D485.1.11] [outbound] Looking up A records for: xxxxx.com
2017-04-14T16:04:07.175Z [INFO] [059AD65E-B342-4EEB-A6D5-2588DBA6D485.1.11] [outbound] Attempting to deliver to: XX.XX.135.111:25 (0) (0)
2017-04-14T16:04:07.234Z [PROTOCOL] [059AD65E-B342-4EEB-A6D5-2588DBA6D485.1.11] [outbound] C: MAIL FROM:<ppp@yyyyyy.com>
2017-04-14T16:04:07.235Z [PROTOCOL] [059AD65E-B342-4EEB-A6D5-2588DBA6D485.1.11] [outbound] S: 250 2.1.0 Ok\r\n
2017-04-14T16:04:07.235Z [PROTOCOL] [059AD65E-B342-4EEB-A6D5-2588DBA6D485.1.11] [outbound] C: RCPT TO:<ggg@uuuuu.com>
2017-04-14T16:04:07.235Z [PROTOCOL] [059AD65E-B342-4EEB-A6D5-2588DBA6D485.1.11] [outbound] S: 250 2.0.0 Ok\r\n
2017-04-14T16:04:07.235Z [PROTOCOL] [059AD65E-B342-4EEB-A6D5-2588DBA6D485.1.11] [outbound] C: DATA
2017-04-14T16:04:07.236Z [PROTOCOL] [059AD65E-B342-4EEB-A6D5-2588DBA6D485.1.11] [outbound] S: 503 5.5.1 Error: need MAIL command\r\n
2017-04-14T16:04:07.236Z [PROTOCOL] [059AD65E-B342-4EEB-A6D5-2588DBA6D485.1.11] [outbound] C: RSET
2017-04-14T16:04:07.237Z [INFO] [059AD65E-B342-4EEB-A6D5-2588DBA6D485.1.11] [outbound] bouncing mail: 503 5.5.1 Error: need MAIL command
2017-04-14T16:04:07.237Z [DEBUG] [059AD65E-B342-4EEB-A6D5-2588DBA6D485.1.11] [outbound] running bounce hooks

**Comment by baudehlo** [comment] 2017-05-21 22:37
Try the current master and disable outbound pools. Set `pool_concurrency_max=0` in outbound.ini.

**Comment by baudehlo** [comment] 2017-05-25 00:12
Also the error appears to be from the other end, not from Haraka.

**Comment by Synchro** [comment] 2017-06-29 14:25
We've started seeing this too, running 2.8.13. In the first example shown above, the sequence is:

```
[outbound] C: MAIL FROM:XXXXXX@xxx.com
[outbound] C: RCPT TO:YYYYYY@xxx.com
[outbound] S: 250 2.1.0 Sender OK\r\n
```
Unless it's a problem with the pasted log, it looks like Haraka is not waiting for the response to the MAIL command before sending the RCPT?

**Comment by Synchro** [comment] 2017-06-29 14:57
Just got more info on this. Here's an excerpt from my bounce table:

![screen shot 2017-06-29 at 16 54 14](https://user-images.githubusercontent.com/81561/27694228-c68f1fcc-5ceb-11e7-8cc2-31b93b9e6a72.png)

so gmail, m.com and hotmail are all complaining in the same way about command sequences from Haraka - suggests it's on Haraka's end...

**Comment by msimerson** [comment] 2017-06-29 19:23
@Synchro, are you running the latest from master?

**Comment by Synchro** [comment] 2017-06-29 19:24
We updated to 2.8.13 about 2 weeks ago from npm, we're not running HEAD. Do you recommend we update?

**Comment by msimerson** [comment] 2017-06-29 19:26
The @baudehlo comment from May 21 makes me think so.

**Comment by baudehlo** [comment] 2017-06-29 19:36
I'm not sure it'll be fixed, except maybe if you set that variable. I don't really understand why it's happening.

**Comment by webkp** [comment] 2017-07-05 16:13
Had the same issue today again with someone trying to send an email to 93 recipients using smtp_bridge.

outbound.ini
```
pool_timeout=50
pool_concurrency_max = 50
```

I raised pool_concurrency_max to 50 back in March as it was not possible to use master immediately and it was much better afterwards. As a side note: All connections go to the same backend smtp server. 

From the logs it looks like Haraka creates all pool connections until max is reached. The ones that Haraka tries to deliver to right after reaching pool_concurrency_max start to get problems. The first 44 mails went out without any problems. From 45 to 93, 27 mails failed with either:
`503 5.5.1 Error: need MAIL command`
or
`503 5.5.1 Error: need RCPT command`

Part with creation of pool connections:
```
13:57:43.151Z [...1.55] [outbound] Attempting to deliver to: xxxxxxx:25 (0) (0)
13:57:43.151Z [-] [core] [outbound] [outbound::25:xxxxxxx:yyyyyyyy:50] dispense() clients=2 available=0
13:57:43.151Z [-] [core] [outbound] [outbound::25:xxxxxxx:yyyyyyyy:50] createResource() - creating obj - count=49 min=0 max=50
13:57:43.152Z [-] [core] [outbound] host=xxxxxxx port=25 pool_timeout=50 created
13:57:43.152Z [...1.65] [outbound] Attempting to deliver to: xxxxxxx:25 (0) (0)
13:57:43.152Z [-] [core] [outbound] [outbound::25:xxxxxxx:yyyyyyyy:50] dispense() clients=3 available=0
13:57:43.152Z [-] [core] [outbound] [outbound::25:xxxxxxx:yyyyyyyy:50] createResource() - creating obj - count=50 min=0 max=50
13:57:43.152Z [-] [core] [outbound] host=xxxxxxx port=25 pool_timeout=50 created
13:57:43.152Z [...1.60] [outbound] Attempting to deliver to: xxxxxxx:25 (0) (0)
13:57:43.152Z [-] [core] [outbound] [outbound::25:xxxxxxx:yyyyyyyy:50] dispense() clients=4 available=0
13:57:43.152Z [...1.66] [outbound] Attempting to deliver to: xxxxxxx:25 (0) (0)
13:57:43.152Z [-] [core] [outbound] [outbound::25:xxxxxxx:yyyyyyyy:50] dispense() clients=5 available=0
13:57:43.153Z [...1.67] [outbound] Attempting to deliver to: xxxxxxx:25 (0) (0)
```

A good transaction (without auth, re-using pool connection I guess)
```
13:57:39.509Z [...1.61] [outbound] running send_email hooks
13:57:39.509Z [...1.61] [outbound] Sending mail: 1499263056093_0_16635_8254.xxxxxxx 
13:57:39.509Z [...1.61] [outbound] running get_mx hooks 
13:57:39.509Z [...1.61] [outbound] running get_mx hook in queue/smtp_bridge plugin
13:57:39.509Z [...1.61] [outbound] hook=get_mx plugin=queue/smtp_bridge function=hook_get_mx params="xxxxxxx" retval=OK msg="[object Object]"
13:57:39.509Z [...1.61] [outbound] Got an MX from Plugin: xxxxxxx => 0 [object Object]
13:57:39.509Z [...1.61] [outbound] Looking up A records for: xxxxxxx
13:57:43.154Z [...1.61] [outbound] Attempting to deliver to: xxxxxxx:25 (0) (0)
13:57:44.706Z [...1.61] [outbound] C: MAIL FROM:<xxxxxxx>
13:57:44.769Z [...1.61] [outbound] S: 250 2.0.0 Ok\r\n
13:57:44.769Z [...1.61] [outbound] C: RCPT TO:<xxxxxxx>
13:57:44.769Z [...1.61] [outbound] S: 250 2.1.0 Ok\r\n
13:57:44.769Z [...1.61] [outbound] C: DATA
13:57:44.769Z [...1.61] [outbound] S: 250 2.0.0 Ok\r\n
13:57:44.770Z [...1.61] [outbound] S: 250 2.1.0 Ok\r\n
13:57:44.831Z [...1.61] [outbound] S: 250 2.1.5 Ok\r\n
13:57:44.831Z [...1.61] [outbound] S: 354 End data with <CR><LF>.<CR><LF>\r\n
13:57:51.242Z [...1.61] [outbound] C: .
13:57:51.291Z [...1.61] [outbound] C: .
13:57:51.291Z [...1.61] [outbound] C: .
13:57:51.352Z [...1.61] [outbound] C: .
13:57:53.486Z [...1.61] [outbound] S: 250 2.0.0 Ok: queued as B9EC32A64641\r\n
13:57:53.486Z [...1.61] [outbound] delivered file=1499263056093_0_16635_8254.xxxxxxx domain="xxxxxxx" host="xxxxxxx" ip=xxxxxxx port=25 mode=SMTP tls=N auth=N response="Ok: queued as B9EC32A64641" delay=17.393 fails=0 rcpts=1/0/0
13:57:53.486Z [...1.61] [outbound] running delivered hooks
13:57:53.486Z [...1.61] [outbound] C: RSET
```

Failing one:
```
13:57:39.509Z [...1.60] [outbound] running send_email hooks
13:57:39.509Z [...1.60] [outbound] Sending mail: 1499263055978_0_16635_8253.xxxxxxx
13:57:39.509Z [...1.60] [outbound] running get_mx hooks
13:57:39.509Z [...1.60] [outbound] running get_mx hook in queue/smtp_bridge plugin
13:57:39.509Z [...1.60] [outbound] hook=get_mx plugin=queue/smtp_bridge function=hook_get_mx params="xxxxxxx" retval=OK msg="[object Object]"
13:57:39.509Z [...1.60] [outbound] Got an MX from Plugin: xxxxxxx => 0 [object Object]
13:57:39.509Z [...1.60] [outbound] Looking up A records for: xxxxxxx
13:57:43.152Z [...1.60] [outbound] Attempting to deliver to: xxxxxxx:25 (0) (0)
13:57:44.389Z [...1.60] [outbound] C: MAIL FROM:<xxxxxxx>
13:57:44.524Z [...1.60] [outbound] S: 250 2.1.0 Ok\r\n
13:57:44.524Z [...1.60] [outbound] C: RCPT TO:<xxxxxxx>
13:57:44.524Z [...1.60] [outbound] S: 250 2.0.0 Ok\r\n
13:57:44.524Z [...1.60] [outbound] C: DATA
13:57:44.583Z [...1.60] [outbound] S: 503 5.5.1 Error: need MAIL command\r\n
13:57:44.583Z [...1.60] [outbound] C: RSET
13:57:44.584Z [...1.60] [outbound] bouncing mail: 503 5.5.1 Error: need MAIL command
13:57:44.584Z [...1.60] [outbound] running bounce hooks
```

If there is anything else from the logs you would need, pls let me know.

**Comment by spathon** [comment] 2017-07-07 08:04
We are still having the issue after setting `pool_concurrency_max=0`

**Comment by webkp** [comment] 2017-07-07 08:18
A quick fix for us would be raising `pool_concurrency_max` to for example 200.
Is there anything we should consider or is this going to work perfectly fine with a such a high concurrency?
(Version: 2.8.13!)

**Comment by baudehlo** [comment] 2017-07-07 14:50
Note that setting pool_concurrency_max=0 would only work (if it works at
all) on current master branch, not on 2.8.13.

**Comment by webkp** [comment] 2017-07-07 15:01
That's why I try to raise it - if this won't be a problem? I know that setting to 0 is not possible with 2.8.13

**Comment by baudehlo** [comment] 2017-07-07 15:30
That's what I'm saying - I can't replicate this bug so I don't know for
certain if this will fix it.

**Comment by Synchro** [comment] 2017-07-07 15:33
@baudehlo Would it help to have access to a server that it's happening on?

**Comment by baudehlo** [comment] 2017-07-07 15:33
Only if you want to install master on it.

**Comment by Synchro** [comment] 2017-07-07 15:46
We're up for that. Please contact me via my profile and I'll sort out access.

**Comment by webkp** [comment] 2017-07-07 16:31
Could you guys keep this issue updated with your findings? I'm very interested in it. 

As we only have this problem with single emails that have more recipients than `pool_concurrency_max` I'll try the rate limit plugin in the meantime to have senders split up their emails.

**Comment by Synchro** [comment] 2017-07-07 16:33
Sure. We are only ever sending messages with a single recipient, so it doesn't sound like that is relevant.

**Comment by baudehlo** [comment] 2017-07-07 16:57
Hmm that's an odd aspect of what you're seeing. It really shouldn't matter. Do you have always_split set?

**Comment by webkp** [comment] 2017-07-07 17:41
Ok, weird. But I have to tell you that's the only moment we're reaching pool_concurrency_max as the load is much lower normally and wouldn't reach this number. So probably we would see it with single recipients too with enough load. always_split is off but that's anyway only for same-domain recipients and I checked, the last time it happened the recipients were very different and not on the same domain.

However, I just read about pool_timeout:

> Setting this value to 0 will effectively disable the use of pools. You may wish to set this if you have a get_mx hook that picks outbound servers on a per-email basis (rather than per-domain).

We're actually using get_mx hooks and pool_timeout is not 0 but left at default

**Comment by baudehlo** [comment] 2017-07-07 18:21
Sorry those docs are a bit broken now.

It's pool_concurrency_max that disables pooling. With pool_timeout = 0 it
still goes through the pool code (i.e. sends a RSET at the end) but then
immediately tries to QUIT on release to the pool. It should probably never
be set to zero and the docs need updated to mention pool_concurrency_max
instead.

**Comment by webkp** [comment] 2017-07-07 19:00
Got that but couldn't that solve our problem? If an RSET is sent and the connection gets quit we won't reach pool_concurrency_max. We use Haraka as auth_proxy / smtp_bridge. Once a customer tries to AUTH we lookup his backend server and proxy the AUTH there. If he sends an email this will be proxied to the backend server (get_mx hook) and sent from there. Incoming mails go to backend servers directly. So we don't bother if there are some more connections open between Haraka and the backend smtp server.

**Comment by baudehlo** [comment] 2017-07-07 19:12
I don't know. Try it.

Until I get to spend a few hours on this problem I won't be able to fix the
underlying bug.

**Comment by webkp** [comment] 2017-07-07 19:16
I'll do, thank you. 

Sure, no problem. Maybe anyway not worth it if the pooling changes with the next release/current master.

**Comment by Synchro** [comment] 2017-07-11 09:11
@baudehlo Do you still want access?

**Comment by baudehlo** [comment] 2017-07-11 13:00
At some point yes, but I have no internet right now except at work. They
are supposed to be fixing it tomorrow.

**Comment by Synchro** [comment] 2017-07-22 13:05
Any progress on this?

**Comment by baudehlo** [comment] 2017-07-22 15:10
None. I doubt I'll get chance. You might have to dig into the mystery yourself.

**Comment by spathon** [comment] 2017-07-25 14:18
We ended up downgrading as master gave us to much errors to look in to now

**Comment by adelphes** [comment] 2017-08-29 12:41
Haraka | Haraka.js — Version: 2.8.14
 --- | :--- 
Node | v6.11.2
OS | Linux xxxxxxx 4.4.0-92-generic 115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.2g  1 Mar 2016

We have also started seeing this problem with pooled connections to gmail's SMTP server bouncing outbound messages from Haraka.

```
2017-08-29T08:27:44.928Z [INFO] [-] [core] [outbound] Created transaction: 756E2355-1BAE-4A17-8BA6-CD97FDBC27EA
2017-08-29T08:27:45.261Z [INFO] [756E2355-1BAE-4A17-8BA6-CD97FDBC27EA.1] [outbound] hook=get_mx plugin=get_smtp_forward function=get_forwarding_hop params="somedomain.com" retval=OK msg="[object Object]"
2017-08-29T08:27:45.261Z [INFO] [756E2355-1BAE-4A17-8BA6-CD97FDBC27EA.1] [outbound] Looking up A records for: smtp-relay.gmail.com
2017-08-29T08:27:45.263Z [INFO] [756E2355-1BAE-4A17-8BA6-CD97FDBC27EA.1] [outbound] Attempting to deliver to: 209.85.203.28:587 (0) (0)
2017-08-29T08:27:45.942Z [INFO] [756E2355-1BAE-4A17-8BA6-CD97FDBC27EA.1] [outbound] bouncing mail: 503 5.5.1 MAIL first. h33sm199417wrh.10 - gsmtp
```

We are generally seeing it happen when an outbound message is being sent to multiple domains via the same relay (gmail's in this case). The message is split into 1 tx per recipient and one or two will fail with the above error.

**Comment by adelphes** [comment] 2017-08-30 11:31
Further investigation has shown that a pooled connection is being released before the final RSET command is sent. The reused socket sends a MAIL command followed by the RSET from the previous transaction.

Reproduction:
- Start with an empty pool (cfg.pool_concurrency_max = 10)
- Send 1 outbound message to 1 recipient (creates one pooled socket connection)
- Wait until delivery is complete and the pooled connection is moved to the 'available' state
- Send 1 outbound message to multiple recipients across multiple domains (my example used 3 rcpts)
- Multiple pooled connections are created and the first connection is reused across 2 tx's simultaneously.

Trace (with some notes and additional logging of socket fd's):
```
// successful send to first (of 3) recipients using socket 22
2017-08-30T10:20:30.291Z [INFO] [D43044D3-F216-4222-B41C-938A9EDAD104.1] [outbound] Attempting to deliver to: 127.0.0.1:25 (0) (0)
2017-08-30T10:20:30.291Z [INFO] [-] [core] [outbound] [outbound::25:127.0.0.1:undefined:50] dispense() clients=1 available=1
2017-08-30T10:20:30.291Z [DEBUG] [-] [core] [outbound] [outbound::25:127.0.0.1:undefined:50] dispense() - reusing obj
60070,245667294 aquired socket: 22
[D43044D3-F216-4222-B41C-938A9EDAD104.1] 60070,249503090 try_deliver_host_on_socket: 22
2017-08-30T10:20:30.297Z [DEBUG] [-] [core] [outbound] got pooled socket, trying to deliver
[D43044D3-F216-4222-B41C-938A9EDAD104.1] 60070,251116471 socket write: 22
2017-08-30T10:20:30.298Z [PROTOCOL] [D43044D3-F216-4222-B41C-938A9EDAD104.1] [outbound] C: MAIL FROM:<from_test@localhost>
2017-08-30T10:20:30.299Z [PROTOCOL] [D43044D3-F216-4222-B41C-938A9EDAD104.1] [outbound] S: 250 2.1.0 Ok\r\n
[D43044D3-F216-4222-B41C-938A9EDAD104.1] 60070,253348408 socket write: 22
[D43044D3-F216-4222-B41C-938A9EDAD104.1] 60070,253348408 socket write: 22
2017-08-30T10:20:30.300Z [PROTOCOL] [D43044D3-F216-4222-B41C-938A9EDAD104.1] [outbound] C: RCPT TO:<dave@localhost>
2017-08-30T10:20:30.304Z [PROTOCOL] [D43044D3-F216-4222-B41C-938A9EDAD104.1] [outbound] S: 250 2.1.5 Ok\r\n
[D43044D3-F216-4222-B41C-938A9EDAD104.1] 60070,258632437 socket write: 22
2017-08-30T10:20:30.305Z [PROTOCOL] [D43044D3-F216-4222-B41C-938A9EDAD104.1] [outbound] C: DATA
2017-08-30T10:20:30.306Z [PROTOCOL] [D43044D3-F216-4222-B41C-938A9EDAD104.1] [outbound] S: 354 End data with <CR><LF>.<CR><LF>\r\n
[D43044D3-F216-4222-B41C-938A9EDAD104.1] 60070,261873453 socket write: 22
2017-08-30T10:20:30.309Z [PROTOCOL] [D43044D3-F216-4222-B41C-938A9EDAD104.1] [outbound] C: .

// create new socket for Tx 2 (socket 22 is still in use)
2017-08-30T10:20:30.313Z [INFO] [BBFB6890-4831-44D6-AF5A-E7CD62DA8199.1] [outbound] Attempting to deliver to: 127.0.0.1:25 (2) (0)
2017-08-30T10:20:30.314Z [INFO] [-] [core] [outbound] [outbound::25:127.0.0.1:undefined:50] dispense() clients=1 available=0
2017-08-30T10:20:30.314Z [DEBUG] [-] [core] [outbound] [outbound::25:127.0.0.1:undefined:50] createResource() - creating obj - count=2 min=0 max=10
2017-08-30T10:20:30.316Z [DEBUG] [-] [core] [outbound] host=127.0.0.1 port=25 pool_timeout=50 created

// create new socket for Tx 3 (socket 22 is still in use)
2017-08-30T10:20:30.318Z [INFO] [BBFB6890-4831-44D6-AF5A-E7CD62DA8199.2] [outbound] Attempting to deliver to: 127.0.0.1:25 (1) (0)
2017-08-30T10:20:30.318Z [INFO] [-] [core] [outbound] [outbound::25:127.0.0.1:undefined:50] dispense() clients=2 available=0
2017-08-30T10:20:30.318Z [DEBUG] [-] [core] [outbound] [outbound::25:127.0.0.1:undefined:50] createResource() - creating obj - count=3 min=0 max=10
2017-08-30T10:20:30.318Z [DEBUG] [-] [core] [outbound] host=127.0.0.1 port=25 pool_timeout=50 created

// release socket 22 back to the pool (but we haven't sent the final RSET yet...)
2017-08-30T10:20:30.322Z [DEBUG] [D43044D3-F216-4222-B41C-938A9EDAD104.1] [outbound] running delivered hooks
2017-08-30T10:20:30.322Z [DEBUG] [-] [core] [outbound] release_client: 127.0.0.1:25 to undefined
2017-08-30T10:20:30.322Z [INFO] [-] [core] [outbound] [outbound::25:127.0.0.1:undefined:50] dispense() clients=2 available=1

// start sending Tx 2 - reacquires socket 22
2017-08-30T10:20:30.323Z [DEBUG] [-] [core] [outbound] [outbound::25:127.0.0.1:undefined:50] dispense() - reusing obj
60070,276713639 aquired socket: 22
[BBFB6890-4831-44D6-AF5A-E7CD62DA8199.1] 60070,279178339 try_deliver_host_on_socket: 22
2017-08-30T10:20:30.326Z [DEBUG] [-] [core] [outbound] got pooled socket, trying to deliver
[BBFB6890-4831-44D6-AF5A-E7CD62DA8199.1] 60070,280150748 socket write: 22
2017-08-30T10:20:30.327Z [PROTOCOL] [BBFB6890-4831-44D6-AF5A-E7CD62DA8199.1] [outbound] C: MAIL FROM:<dave@localhost>

// and now we're using socket 22 to send the final RSET command for Tx 1
[D43044D3-F216-4222-B41C-938A9EDAD104.1] 60070,281036734 socket write: 22
2017-08-30T10:20:30.328Z [PROTOCOL] [D43044D3-F216-4222-B41C-938A9EDAD104.1] [outbound] C: RSET

// a short time later....
[BBFB6890-4831-44D6-AF5A-E7CD62DA8199.1] 60070,286124888 socket write: 22
2017-08-30T10:20:30.333Z [PROTOCOL] [BBFB6890-4831-44D6-AF5A-E7CD62DA8199.1] [outbound] C: DATA
2017-08-30T10:20:30.337Z [PROTOCOL] [BBFB6890-4831-44D6-AF5A-E7CD62DA8199.1] [outbound] S: 503 5.5.1 Error: need MAIL command\r\n
```

**Comment by smfreegard** [comment] 2017-08-30 13:54
@adelphes - I've had a really, really quick look at this and I think I've spotted the problem thanks to the time you've spent getting decent logs and analysis.

I've basically made the release of the client back to the pool conditional on receiving an OK response to the RSET.  I'm not 100% confident that this won't introduce some other bugs though.

Can you try this patch (untested):

`````
--- a/outbound/hmail.js
+++ b/outbound/hmail.js
@@ -619,7 +619,7 @@ HMailItem.prototype.try_deliver_host_on_socket = function (mx, host, port, socke
             self.discard();
         }
         if (cfg.pool_concurrency_max) {
-            client_pool.release_client(socket, port, host, mx.bind, fin_sent);
+            send_command('RSET');
         }
         else {
             send_command('QUIT');
@@ -679,7 +679,6 @@ HMailItem.prototype.try_deliver_host_on_socket = function (mx, host, port, socke
                     });
                     send_command(cfg.pool_concurrency_max ? 'RSET' : 'QUIT');
                     processing_mail = false;
-                    client_pool.release_client(socket, port, host, mx.bind);
                     return self.temp_fail("Upstream error: " + code + " " + ((extc) ? extc + ' ' : '') + reason);
                 }
                 else if (code.match(/^4/)) {
@@ -718,7 +717,6 @@ HMailItem.prototype.try_deliver_host_on_socket = function (mx, host, port, socke
                         });
                         send_command(cfg.pool_concurrency_max ? 'RSET' : 'QUIT');
                         processing_mail = false;
-                        client_pool.release_client(socket, port, host, mx.bind);
                         return self.temp_fail("Upstream error: " + code + " " + ((extc) ? extc + ' ' : '') + reason);
                     }
                 }
@@ -760,7 +758,6 @@ HMailItem.prototype.try_deliver_host_on_socket = function (mx, host, port, socke
                         });
                         send_command(cfg.pool_concurrency_max ? 'RSET' : 'QUIT');
                         processing_mail = false;
-                        client_pool.release_client(socket, port, host, mx.bind);
                         return self.bounce(reason, { mx: mx });
                     }
                 }
@@ -814,7 +811,6 @@ HMailItem.prototype.try_deliver_host_on_socket = function (mx, host, port, socke
                             }
                             else {
                                 finish_processing_mail(false);
-                                if (cfg.pool_concurrency_max) send_command('RSET');
                             }
                         }
                         else {
@@ -838,7 +834,6 @@ HMailItem.prototype.try_deliver_host_on_socket = function (mx, host, port, socke
                         break;
                     case 'dot':
                         finish_processing_mail(true);
-                        if (cfg.pool_concurrency_max) send_command('RSET');
                         break;
                     case 'dot_lmtp':
                         if (code.match(/^2/)) lmtp_rcpt_idx++;
@@ -855,6 +850,7 @@ HMailItem.prototype.try_deliver_host_on_socket = function (mx, host, port, socke
                         }
                         break;
                     case 'rset':
+                        client_pool.release_client(socket, port, host, mx.bind, fin_sent);
                         break;
                     default:
                         // should never get here - means we did something
@@ -867,6 +863,7 @@ HMailItem.prototype.try_deliver_host_on_socket = function (mx, host, port, socke
             // Unrecognized response.
             self.logerror("Unrecognized response from upstream server: " + line);
             processing_mail = false;
+            // TODO: We should probably destory this connection rather than put it back in the pool
             client_pool.release_client(socket, port, host, mx.bind);
             self.todo.rcpt_to.forEach(function (rcpt) {
                 self.extend_rcpt_with_dsn(rcpt, DSN.proto_invalid_command("Unrecognized response from upstream server: " + line));
`````

**Comment by adelphes** [comment] 2017-08-30 16:03
@smfreegard the patch introduces a new issue.

After `dot` is OK'd by the server, calling `finish_processing_mail(true)` sets `processing_mail=false`. 
This means that when the RSET is OK'd, it's treated as an extra response after we've finished:

`Received data after stopping processing: 250 2.0.0 Ok\r\n`

It's then discarded meaning the `release_client()` is never called.
For some reason (maybe protocol-related) the RSET sent in the original code never receives a response.

I'm looking into an improved fix...

**Comment by smfreegard** [comment] 2017-08-30 16:08
That is trivial to fix:

Change this line:

https://github.com/haraka/Haraka/blob/86771aa67a8135caf454a1a26224027a5364cb81/outbound/hmail.js#L630

to 

`````
        if (!processing_mail && command !== 'rset') {
`````

**Comment by adelphes** [comment] 2017-08-30 16:55
@smfreegard the patch and fix seems to work with my (basic) test case, but I want to run some additional tests.

There does seem to be a lot of `processing_mail=false`, `finish_processing_mail()` and `release_client()` scattered about which might still break stuff - particularly since `finish_processing_mail()` now creates a  RSET call. 

I'm fairly sure there's going to be cases where the connection isn't released (or released prematurely), but at least the "normal" multiple-tx case seems stable.

**Comment by smfreegard** [comment] 2017-08-30 17:01
If you look at the code before my changes - `finish_processing_mail()` was always followed by a `release_client()`.

I reviewed the other places that `release_client()` was called and none of them looked problematic to me.

What I'm basically saying is that I don't have a horse in this particular race, so if you want me to look at and fix something, then show me it broken as I do not have the time or inclination at the moment to thoroughly go through and test every area of this code myself - particularly as I don't use it myself in my own commercial product.

**Comment by KingNoosh** [comment] 2017-08-31 10:03
Would it be worth PR-ing the changes above to fix this issue for others at the very least?

**Comment by baudehlo** [comment] 2017-08-31 10:36
Yes.

**Comment by KingNoosh** [comment] 2017-09-01 20:48
Fixed in https://github.com/haraka/Haraka/pull/2064

**Closed by KingNoosh** 2017-09-01 20:48 UTC
Labels: Bug
