### ISSUE TITLE
TLS certificates from config/tls directory not loaded

### ISSUE THREAD

**Issue by spajak** [haraka/Haraka#2932] opened 2021-03-08 21:56 UTC
**Describe the bug**

Function `getSocketOpts` is never called.
So function `get_certs_dir` is never called.
Certificates from `config/tls` are never loaded.

```
// tls_socket.js

exports.getSocketOpts = (name, done) => {
...
    tlss.get_certs_dir('tls', () => {
        if (certsByHost[name]) {
...
```

**Expected behavior**

Certificates from `config/tls` should be loaded.

**Reproduce**

Log this anywhere (it is always `*`):
```
Object.keys(certsByHost).join(', ');
```

Haraka version 2.8.27. SMTP server only

**Comment by msimerson** [comment] 2021-03-08 22:27
Duplicate of #2905

**Closed by msimerson** 2021-03-08 22:27 UTC
