### ISSUE TITLE
 Error: socket hang up

### ISSUE THREAD

**Issue by darkpixel** [haraka/Haraka#1638] opened 2016-10-05 15:34 UTC
### Haraka version

2.8.9
### node.js

v4.6.0
### Observed behavior

```
[INFO] [D581ABCE-6FFB-44A6-A2F0-83A77D6DDC3D.1] [spf] identity=mfrom ip=216.27.63.138 domain="e.medalsofamerica.com" mfrom=<l7cf48ypokzmjoelkmyj1rzgtplsrjfm-b@e.medalsofamerica.com> result=Pass
[INFO] [D581ABCE-6FFB-44A6-A2F0-83A77D6DDC3D.1] [spf] scope: mfrom, result: Pass, domain: e.medalsofamerica.com
[NOTICE] [D581ABCE-6FFB-44A6-A2F0-83A77D6DDC3D.1] [core] sender <l7cf48ypokzmjoelkmyj1rzgtplsrjfm-b@e.medalsofamerica.com> code=CONT msg=""
[CRIT] [-] [core] Error: socket hang up
[CRIT] [-] [core]     at TLSSocket.onHangUp (_tls_wrap.js:1054:19)
[CRIT] [-] [core]     at TLSSocket.g (events.js:260:16)
[CRIT] [-] [core]     at emitNone (events.js:72:20)
[CRIT] [-] [core]     at TLSSocket.emit (events.js:166:7)
[CRIT] [-] [core]     at endReadableNT (_stream_readable.js:921:12)
[CRIT] [-] [core]     at nextTickCallbackWith2Args (node.js:442:9)
[CRIT] [-] [core]     at process._tickCallback (node.js:356:17)
[NOTICE] [-] [core] Shutting down
[NOTICE] [-] [core] worker 3 exited with error code: 1
[NOTICE] [-] [core] worker 10 started pid=29147
```
### Steps to reproduce

Frequently incoming mail will cause the worker to bomb with this error.

**Comment by smfreegard** [comment] 2016-10-05 15:57
I've just tried to reproduce this, but I haven't been able to so far.   Which version of node are you running?

**Comment by darkpixel** [comment] 2016-10-05 16:14
```v4.6.0```

**Comment by darkpixel** [comment] 2016-10-05 16:27
Bumped up to 5.x and the issue disappears.

**Comment by msimerson** [comment] 2016-10-05 17:48
> Bumped up to 5.x and the issue disappears.

Oh dear. Maybe I need to add node.js version in the new issue template.

**Comment by baudehlo** [comment] 2016-10-05 18:33
That is a good idea.

**Comment by darkpixel** [comment] 2016-10-11 16:13
Bumped up to v6.7.0 as a test and the issue comes back.

**Comment by Dexus** [comment] 2016-10-13 20:13
OS? OpenSSL version?

On CentOS 7 please install node and openssl from source, that should help you to fix this problem.

**Comment by darkpixel** [comment] 2016-10-14 21:44
```
root@mx1:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.6 (jessie)
Release:	8.6
Codename:	jessie
root@mx1:~# openssl version
OpenSSL 1.0.1t  3 May 2016
root@mx1:~# uname -a
Linux mx1 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux
root@mx1:~# 
```

**Comment by Dexus** [comment] 2016-10-14 22:57
Can you try to use the backport openssl 1.0.2 for jessie?
I think its a nodejs / TLS problem, and in the last time i have also seen more problems with the different versions of openssl and node.

Is the sender a regular sender or a spamer?

I'm not able to reproduce this issue. Have now switched to a test system to heavy load live system maybe there i can see the problem.

**Comment by darkpixel** [comment] 2016-10-14 22:59
I'm on vacation for a week.  I'll dive in to it when I'm back at the office.

**Comment by typingArtist** [comment] 2016-10-24 17:44
@darkpixel, can you retry with the latest official version v2.8.10? There have been changes to the TLS code which might affect your problem. More patches sitting on PRs, so perhaps the issue goes away with the updated error handling.

**Comment by darkpixel** [comment] 2016-10-24 18:10
Yeah.  I just got back in the office today.  I have a handful of things to take care of, and then I get to dive back into e-mail stuff tomorrow.  I'll let you know.

**Comment by darkpixel** [comment] 2016-10-25 16:23
I just pulled from head and it blew up.
```
[INFO] [30AF45AE-9611-4EEF-B840-EC55ED8979C8.1.1] [outbound] Looking up A records for: barracuda.welovesmiles.com
[INFO] [30AF45AE-9611-4EEF-B840-EC55ED8979C8.1.1] [outbound] Attempting to deliver to: 198.0.46.123:25 (0) (1)
[INFO] [-] [core] [outbound] [outbound::25:198.0.46.123:undefined:50] dispense() clients=1 available=0
[CRIT] [-] [core] TypeError: Path must be a string. Received undefined
[CRIT] [-] [core]     at assertPath (path.js:8:11)
[CRIT] [-] [core]     at Object.posix.resolve (path.js:426:5)
[CRIT] [-] [core]     at Config.get (/usr/lib/node_modules/Haraka/config.js:28:26)
[CRIT] [-] [core]     at pluggableStream.<anonymous> (/usr/lib/node_modules/Haraka/outbound.js:1723:50)
[CRIT] [-] [core]     at emitOne (events.js:77:13)
[CRIT] [-] [core]     at pluggableStream.emit (events.js:169:7)
[CRIT] [-] [core]     at pluggableStream.socket.process_data (/usr/lib/node_modules/Haraka/line_socket.js:23:20)
[CRIT] [-] [core]     at pluggableStream.<anonymous> (/usr/lib/node_modules/Haraka/line_socket.js:34:48)
[CRIT] [-] [core]     at emitOne (events.js:77:13)
[CRIT] [-] [core]     at pluggableStream.emit (events.js:169:7)
[NOTICE] [-] [core] Shutting down
```

I know there have been a lot of changes in the last few weeks.  Let me do some digging and see if I missed some required config changes or something.

**Comment by msimerson** [comment] 2016-10-25 16:32
I see the problem. PR coming soon...

**Comment by msimerson** [comment] 2016-10-25 22:31
Okay @darkpixel , try again now from haraka/Haraka#master. I've merged in a fix and also tested running it on a test VM. I don't have SMTP outbound from my house, but at least I get nice appropriate errors now.

````
Oct 25 15:28:24 haraka haraka[3587]: [ERROR] [-] [core] [outbound] Failed to get pool entry: Outbound connection timed out to x.x.x.x:25
````

**Comment by darkpixel** [comment] 2016-11-05 19:50
This has gone away in the latest version.

**Comment by msimerson** [comment] 2016-11-05 19:55
> This has gone away in the latest version.

Awesome. Thanks for following up.

**Comment by darkpixel** [comment] 2016-11-05 20:02
Yup.  Sorry for the delays and being a zombie in the channel--I've been slammed for the last ~6 weeks.

**Closed** 2016-11-16 20:50 UTC
