### ISSUE TITLE
Office 365 session times out after 20 mins with smtp_forward

### ISSUE THREAD

**Issue by kkr78** [haraka/Haraka#2321] opened 2018-01-22 17:09 UTC
### system info

Haraka 2.8.16
OS | Linux ip-40-4-21-5 4.9.62-21.56.amzn1.x86_64 #1 SMP Thu Nov 16 05:37:08 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

smtp_forward.ini settings

```ini
[xxx.com]
host=xxx-com.mail.protection.outlook.com
port=25
enable_tls=true
timeout=300
connect_timeout=320
```

### Expected behavior

Office 365 throwing an error after 20 mins. is it possible to recreate the connection and retry on a specific error in Haraka ex: 450 error code? are there any pool settings to close the active connection after a certain period ex: 15 mins? I see in logs, the SMTP forward using the pool timeout. where is it reading from?

### Observed behavior

Haraka created the connection: 2018-01-22T13:16:05.989Z closed the connection: 2018-01-22T13:37:01.458Z after receiving the "4.4.1 Connection timed out. Total session duration: 00:20:55.2872355".  The issue is very consistent. I can see these errors for almost every connection.  Please see below, the connection closed right after it received session timeout message. 

Full error message

2018-01-22T13:37:01.457Z [INFO] [960286F2-16F2-48DF-B2A5-6BEB06B76F7D.1] [core]  hook=queue plugin=queue/smtp_forward function=queue_forward params="" retval=DENYSOFT msg="4.4.1 Connection timed out. Total session duration: 00:20:55.2872355 [xxx.xxx.xxx.protection.outlook.com]"

Here is the connection usage uuid=A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18. 

2018-01-22T13:16:05.989Z [DEBUG] [-] [core] [smtp_client_pool] uuid=A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18 host=xxx-com.mail.protection.outlook.com port=25 pool_timeout=300 created
2018-01-22T13:16:05.989Z [DEBUG] [DDC9F505-2AC2-4110-9475-0750E4664088.1] [queue/smtp_forward] Got smtp_client: A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18
2018-01-22T13:16:07.498Z [DEBUG] [-] [core] [smtp_client_pool] A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18 resetting, state=2
2018-01-22T13:16:07.575Z [DEBUG] [-] [core] [smtp_client_pool] A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18 releasing, state=3
2018-01-22T13:18:51.048Z [DEBUG] [5AB25349-9B61-4D62-AE16-AAFCC3D3BA4A.1] [queue/smtp_forward] Got smtp_client: A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18
2018-01-22T13:18:51.762Z [DEBUG] [-] [core] [smtp_client_pool] A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18 resetting, state=2
2018-01-22T13:18:51.839Z [DEBUG] [-] [core] [smtp_client_pool] A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18 releasing, state=3
2018-01-22T13:19:50.804Z [DEBUG] [2037B9FC-F640-47DF-83AB-E5598E9E23DE.1] [queue/smtp_forward] Got smtp_client: A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18
2018-01-22T13:19:51.401Z [DEBUG] [-] [core] [smtp_client_pool] A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18 resetting, state=2
2018-01-22T13:19:51.478Z [DEBUG] [-] [core] [smtp_client_pool] A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18 releasing, state=3
2018-01-22T13:24:43.041Z [DEBUG] [8A7B9AE5-FC7C-47FC-AD0E-2E51CF01FA57.1] [queue/smtp_forward] Got smtp_client: A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18
2018-01-22T13:24:43.751Z [DEBUG] [-] [core] [smtp_client_pool] A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18 resetting, state=2
2018-01-22T13:24:43.828Z [DEBUG] [-] [core] [smtp_client_pool] A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18 releasing, state=3
2018-01-22T13:26:01.042Z [DEBUG] [1CC819AF-A4AA-4D31-A5A6-8AD7B2BB5C82.1] [queue/smtp_forward] Got smtp_client: A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18
2018-01-22T13:26:01.825Z [DEBUG] [-] [core] [smtp_client_pool] A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18 resetting, state=2
2018-01-22T13:26:01.905Z [DEBUG] [-] [core] [smtp_client_pool] A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18 releasing, state=3
2018-01-22T13:26:34.597Z [DEBUG] [2FAE95E5-EA11-4F29-8C22-214C90F545C0.1] [queue/smtp_forward] Got smtp_client: A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18
2018-01-22T13:26:35.461Z [DEBUG] [-] [core] [smtp_client_pool] A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18 resetting, state=2
2018-01-22T13:26:35.538Z [DEBUG] [-] [core] [smtp_client_pool] A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18 releasing, state=3
2018-01-22T13:31:31.361Z [DEBUG] [45FF3CC5-A5F4-47D8-A843-8E54C72361A4.1] [queue/smtp_forward] Got smtp_client: A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18
2018-01-22T13:31:32.148Z [DEBUG] [-] [core] [smtp_client_pool] A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18 resetting, state=2
2018-01-22T13:31:32.226Z [DEBUG] [-] [core] [smtp_client_pool] A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18 releasing, state=3
2018-01-22T13:35:40.516Z [DEBUG] [9A984CCB-B100-4516-87B6-8ECACCCF072C.1] [queue/smtp_forward] Got smtp_client: A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18
2018-01-22T13:35:41.910Z [DEBUG] [-] [core] [smtp_client_pool] A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18 resetting, state=2
2018-01-22T13:35:41.988Z [DEBUG] [-] [core] [smtp_client_pool] A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18 releasing, state=3
2018-01-22T13:37:01.379Z [DEBUG] [960286F2-16F2-48DF-B2A5-6BEB06B76F7D.1] [queue/smtp_forward] Got smtp_client: A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18
2018-01-22T13:37:01.457Z [DEBUG] [-] [core] [smtp_client_pool] A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18 resetting, state=2
2018-01-22T13:37:01.458Z [DEBUG] [-] [core] [smtp_client_pool] A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18 destroyed, state=3

2018-01-22T13:37:01.458Z [DEBUG] [-] [core] [smtp_client_pool] A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18: [xxx-com.mail.protection.outlook.com:25] SMTP connection ended  (state=4)
2018-01-22T13:37:01.458Z [DEBUG] [-] [core] [smtp_client_pool] A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18: [xxx-com.mail.protection.outlook.com:25] SMTP connection closed  (state=4)

### Steps to reproduce

Setup smtp forward to office 365
Forward messages for 25 mins

**Comment by KingNoosh** [comment] 2018-01-22 17:14
Is your instance of Haraka hosted somewhere like AWS for example?


On Mon, Jan 22, 2018 at 5:10pm, kkr78 < notifications@github.com [notifications@github.com] > wrote:
SYSTEM INFO
Haraka 2.8.16
OS | Linux ip-40-4-21-5 4.9.62-21.56.amzn1.x86_64 #1 [https://github.com/haraka/Haraka/pull/1] SMP Thu Nov 16 05:37:08 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

smtp_forward.ini settings

[xxx.com]
host=xxx-com.mail.protection.outlook.com
port=25
enable_tls=true
timeout=300
connect_timeout=320

EXPECTED BEHAVIOR
Office 365 throwing an error after 20 mins. is it possible to recreate the connection and retry on a specific error in Haraka? are there any pool settings to close the active connection after a certain period ex: 15 mins? I see in logs, the SMTP forward using the pool timeout. where is it reading from?

OBSERVED BEHAVIOR
Haraka created the connection: 2018-01-22T13:16:05.989Z and closed the connection: 2018-01-22T13:37:01.458Z after receiving the "4.4.1 Connection timed out. Total session duration: 00:20:55.2872355". The issue is very consistent. I can see these errors for almost every connection. Please see below, the connection closed right after it received session timeout message.

Full error message

2018-01-22T13:37:01.457Z [INFO] [960286F2-16F2-48DF-B2A5-6BEB06B76F7D.1] [core] hook=queue plugin=queue/smtp_forward function=queue_forward params="" retval=DENYSOFT msg="4.4.1 Connection timed out. Total session duration: 00:20:55.2872355 [xxx.xxx.xxx.protection.outlook.com]"

Here is the connection usage uuid=A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18.

2018-01-22T13:16:05.989Z [DEBUG] [-] [core] [smtp_client_pool] uuid=A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18 host=xxx-com.mail.protection.outlook.com port=25 pool_timeout=300 created
2018-01-22T13:16:05.989Z [DEBUG] [DDC9F505-2AC2-4110-9475-0750E4664088.1] [queue/smtp_forward] Got smtp_client: A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18
2018-01-22T13:16:07.498Z [DEBUG] [-] [core] [smtp_client_pool] A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18 resetting, state=2
2018-01-22T13:16:07.575Z [DEBUG] [-] [core] [smtp_client_pool] A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18 releasing, state=3
2018-01-22T13:18:51.048Z [DEBUG] [5AB25349-9B61-4D62-AE16-AAFCC3D3BA4A.1] [queue/smtp_forward] Got smtp_client: A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18
2018-01-22T13:18:51.762Z [DEBUG] [-] [core] [smtp_client_pool] A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18 resetting, state=2
2018-01-22T13:18:51.839Z [DEBUG] [-] [core] [smtp_client_pool] A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18 releasing, state=3
2018-01-22T13:19:50.804Z [DEBUG] [2037B9FC-F640-47DF-83AB-E5598E9E23DE.1] [queue/smtp_forward] Got smtp_client: A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18
2018-01-22T13:19:51.401Z [DEBUG] [-] [core] [smtp_client_pool] A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18 resetting, state=2
2018-01-22T13:19:51.478Z [DEBUG] [-] [core] [smtp_client_pool] A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18 releasing, state=3
2018-01-22T13:24:43.041Z [DEBUG] [8A7B9AE5-FC7C-47FC-AD0E-2E51CF01FA57.1] [queue/smtp_forward] Got smtp_client: A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18
2018-01-22T13:24:43.751Z [DEBUG] [-] [core] [smtp_client_pool] A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18 resetting, state=2
2018-01-22T13:24:43.828Z [DEBUG] [-] [core] [smtp_client_pool] A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18 releasing, state=3
2018-01-22T13:26:01.042Z [DEBUG] [1CC819AF-A4AA-4D31-A5A6-8AD7B2BB5C82.1] [queue/smtp_forward] Got smtp_client: A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18
2018-01-22T13:26:01.825Z [DEBUG] [-] [core] [smtp_client_pool] A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18 resetting, state=2
2018-01-22T13:26:01.905Z [DEBUG] [-] [core] [smtp_client_pool] A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18 releasing, state=3
2018-01-22T13:26:34.597Z [DEBUG] [2FAE95E5-EA11-4F29-8C22-214C90F545C0.1] [queue/smtp_forward] Got smtp_client: A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18
2018-01-22T13:26:35.461Z [DEBUG] [-] [core] [smtp_client_pool] A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18 resetting, state=2
2018-01-22T13:26:35.538Z [DEBUG] [-] [core] [smtp_client_pool] A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18 releasing, state=3
2018-01-22T13:31:31.361Z [DEBUG] [45FF3CC5-A5F4-47D8-A843-8E54C72361A4.1] [queue/smtp_forward] Got smtp_client: A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18
2018-01-22T13:31:32.148Z [DEBUG] [-] [core] [smtp_client_pool] A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18 resetting, state=2
2018-01-22T13:31:32.226Z [DEBUG] [-] [core] [smtp_client_pool] A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18 releasing, state=3
2018-01-22T13:35:40.516Z [DEBUG] [9A984CCB-B100-4516-87B6-8ECACCCF072C.1] [queue/smtp_forward] Got smtp_client: A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18
2018-01-22T13:35:41.910Z [DEBUG] [-] [core] [smtp_client_pool] A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18 resetting, state=2
2018-01-22T13:35:41.988Z [DEBUG] [-] [core] [smtp_client_pool] A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18 releasing, state=3
2018-01-22T13:37:01.379Z [DEBUG] [960286F2-16F2-48DF-B2A5-6BEB06B76F7D.1] [queue/smtp_forward] Got smtp_client: A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18
2018-01-22T13:37:01.457Z [DEBUG] [-] [core] [smtp_client_pool] A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18 resetting, state=2
2018-01-22T13:37:01.458Z [DEBUG] [-] [core] [smtp_client_pool] A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18 destroyed, state=3

2018-01-22T13:37:01.458Z [DEBUG] [-] [core] [smtp_client_pool] A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18: [contactcwt-com.mail.protection.outlook.com:25] SMTP connection ended (state=4)
2018-01-22T13:37:01.458Z [DEBUG] [-] [core] [smtp_client_pool] A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18: [xxx-com.mail.protection.outlook.com:25] SMTP connection closed (state=4)

STEPS TO REPRODUCE
Setup smtp forward to office 365
Forward messages for 25 mins

**Comment by KingNoosh** [comment] 2018-01-23 09:57
AWS throttles sending outbound mail from EC2 instances, you need to request to support to lift those limits on each region and elastic ip addresses.

**Comment by kkr78** [comment] 2018-01-23 13:04
Throttle removed on those servers. I don't think it's an issue with that. Office 365 SMTP server (xxx-com.mail.protection.outlook.com) is timing out on the established connection after 20 mins. It looks like Office 365 expects to cache the connection only 20 mins. Please see above attached the logs which shows this error message -->"4.4.1 Connection timed out. Total session duration: 00:20:55.2872355".  I haven't configured any pool params other than specified in smtp_forward.ini (which configured with timeout=300 connect_timeout=320).  It appears smtp_client is creating the connection using default pool params (for ex: pool_timeout). How does Haraka handle the connection errors? is it possible to configure Haraka to retry when it encounters connection timeout error? where can I configure the pool params? 

This is what happened

1) For the first message, Haraka opened connection in the pool (id#A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18)

2018-01-22T**13:16:05**.989Z [DEBUG] [-] [core] [smtp_client_pool] uuid=A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18 host=xxx-com.mail.protection.outlook.com port=25 pool_timeout=300 created

2) Subsequent requests reused the above connection as expected

3) After 20 mins, Haraka received the following error from Office 365. Haraka returned 450 to the client and closed the connection.

"4.4.1 Connection timed out. Total session duration: 00:20:55.2872355"

2018-01-22T**13:37:01**.458Z [DEBUG] [-] [core] [smtp_client_pool] A8CC25F4-D1F7-4DF8-9EAE-FFC689A0CC18: [xxx-com.mail.protection.outlook.com:25] SMTP connection closed (state=4)

**Comment by KingNoosh** [comment] 2018-01-23 19:59
We had the exact same problem and it ended up being AWS, you might want to send AWS a support ticket. We did the same.

**Comment by kkr78** [comment] 2018-01-25 13:35
I just now got confirmation from AWS that it's not an issue with the throttle.  The throttle has been removed a long time back. They reviewed traces and confirmed, its the target SMTP server throwing that error. I opened a case with MS and they confirmed error thrown by their SMTP server. This confirms error indeed came from Office 365/MS Exchange. can we do anything in Haraka to handle this error without impacting the clients? I want Haraka to catch this error, close the connection and resend it. Right now client receiving 450 error.

**Comment by KingNoosh** [comment] 2018-01-25 13:40
That's very strange, I'm going to see if we did anything different to get it working.


On Thu, Jan 25, 2018 at 1:35pm, kkr78 < notifications@github.com [notifications@github.com] > wrote:I just now got confirmation from AWS that it's not an issue with the throttle. The throttle has been removed a long time back. They reviewed traces and confirmed, its the target SMTP server throwing that error. I opened a case with MS and they confirmed error thrown by their SMTP server. This confirms error indeed came from Office 365/MS Exchange. can we do anything in Haraka to handle this error without impacting the clients? I want Haraka to catch this error, close the connection and resend it. Right now client receiving 450 error.

**Comment by msimerson** [comment] 2018-12-23 03:39
@kkr78 , are you still having this issue?  What version of Haraka are you currently running?

If you are having the issue, would you mind testing and seeing if [this patch](https://github.com/haraka/Haraka/commit/3cd61b65b628a4c0b03863a831ed06eebf4c6937) resolves the issue?

**Comment by msimerson** [comment] 2019-01-04 04:58
Closing. We can reopen if someone responds.

**Closed by msimerson** 2019-01-04 04:58 UTC
