### ISSUE TITLE
DKIM: Single domain

### ISSUE THREAD

**Issue by thenitai** [haraka/Haraka#2657] opened 2019-06-10 23:15 UTC
Latest Haraka 2.8.24

I just realized that all outgoing emails fail the DKIM signing process with:

```
2019-06-10T23:11:55.522Z [INFO] [-] [core] [outbound] Sending email as a transaction
2019-06-10T23:11:55.525Z [DEBUG] [-] [dkim_sign] undefined
2019-06-10T23:11:55.526Z [NOTICE] [-] [dkim_sign] skipped: no private key for example.com
2019-06-10T23:11:55.526Z [DEBUG] [-] [core]  hook=pre_send_trans_email plugin=dkim_sign function=hook_pre_send_trans_email params="" retval=CONT msg=""
2019-06-10T23:11:55.526Z [INFO] [-] [core] [outbound] Processing delivery for domain: example.com
2019-06-10T23:11:55.527Z [DEBUG] [-] [core] running pre_send_trans_email hooks
2019-06-10T23:11:55.527Z [DEBUG] [-] [core] running pre_send_trans_email hook in dkim_sign plugin
2019-06-10T23:11:55.534Z [DEBUG] [-] [dkim_sign] undefined
2019-06-10T23:11:55.534Z [NOTICE] [-] [dkim_sign] skipped: no private key for example.com
2019-06-10T23:11:55.535Z [DEBUG] [-] [core]  hook=pre_send_trans_email plugin=dkim_sign function=hook_pre_send_trans_email params="" retval=CONT msg=""
```

I'm not sure, but the issue at https://github.com/haraka/Haraka/issues/2600 seems to be related, no?

Is there any way, I can make this work again? What's the version where this work?

**Comment by msimerson** [comment] 2019-06-10 23:52
You can revert to the version of that file before this change. However, you won't get the `$domain` in the log messages. There's a bit of a chicken-and-egg issue in there that I haven't resolved.

**Comment by thenitai** [comment] 2019-06-11 00:10
Hi Matt,

Thank you for the quick answer. I've tried to get the older version of the file, but I somehow seem to fail to get it on here. I know embarrassing.... :(

Is it the one from August 21, 2018 to take or?

**Comment by thenitai** [comment] 2019-06-11 00:30
Ok, I've grabbed this one:  24a2c8a on Jun 28, 2018  and now it's working again!

Sorry, got up at 4 am and been working non-stop...

**Comment by msimerson** [comment] 2019-06-20 03:14
Duplicate of #2600

**Closed by msimerson** 2019-06-20 03:14 UTC
