### ISSUE TITLE
Mails not sent to some domains, SSL23_GET_SERVER_HELLO:sslv3 alert handshake Error

### ISSUE THREAD

**Issue by vincowl** [haraka/Haraka#2439] opened 2018-06-02 16:53 UTC
While having installed Poste.io using the latest free docker image (analogic/poste.io) which relies on Haraka, I set up my domain, SSL certs through given Let'sEncrypt option. Everything runs fine, I can send and receive mails to and from gmail.com for instance. But as I want to send mails to free.fr (french provider), I have the following error log, and the mail is not sent. I can receive mails from free.fr.

I tested my domain using mxtoolbox.com : everything's fine.... Any idea ?? I am a bit lost : is this an error coming from my container or from free.fr servers ? 

Here is the log from log/delivery/del/...

```
2018-06-02T14:56:13.875Z [1] [DEBUG] [outbound] running send_email hooks
2018-06-02T14:56:13.876Z [1] [DEBUG] [outbound] Sending mail: 1527951373843_1527951373843_0_611_5hphaG_7_<myhostname>
2018-06-02T14:56:13.876Z [1] [DEBUG] [outbound] running get_mx hooks
2018-06-02T14:56:13.876Z [1] [DEBUG] [outbound] running get_mx hook in relay plugin
2018-06-02T14:56:13.876Z [1] [DEBUG] [outbound] hook=get_mx plugin=relay function=force_routing params=free.fr retval=CONT msg=""
2018-06-02T14:56:13.876Z [1] [DEBUG] [outbound] running get_mx hook in rcpt_database plugin
2018-06-02T14:56:13.878Z [1] [DEBUG] [outbound] hook=get_mx plugin=rcpt_database function=hook_get_mx params=free.fr retval=CONT msg=""
2018-06-02T14:56:13.878Z [1] [DEBUG] [outbound] running get_mx hook in queue/lmtp plugin
2018-06-02T14:56:13.878Z [1] [DEBUG] [outbound] hook=get_mx plugin=queue/lmtp function=hook_get_mx params=free.fr retval=CONT msg=""
2018-06-02T14:56:13.912Z [1] [INFO] [outbound] Looking up A records for: mx1.free.fr
2018-06-02T14:56:13.914Z [1] [INFO] [outbound] Attempting to deliver to: 212.27.48.7:25 (0) (6)
2018-06-02T14:56:13.981Z [1] [PROTOCOL] [outbound] S: 220 mx1-g20.free.fr\r\n
2018-06-02T14:56:13.981Z [1] [PROTOCOL] [outbound] C: EHLO <myhostname>
2018-06-02T14:56:14.013Z [1] [PROTOCOL] [outbound] S: 250-mx1-g20.free.fr\r\n
2018-06-02T14:56:14.088Z [1] [PROTOCOL] [outbound] S: 250-STARTTLS\r\n
2018-06-02T14:56:14.088Z [1] [PROTOCOL] [outbound] S: 250-8BITMIME\r\n
2018-06-02T14:56:14.088Z [1] [PROTOCOL] [outbound] S: 250 XFILTERED\r\n
2018-06-02T14:56:14.088Z [1] [PROTOCOL] [outbound] C: STARTTLS
2018-06-02T14:56:14.121Z [1] [PROTOCOL] [outbound] S: 220 2.0.0 Ready to start TLS\r\n
2018-06-02T14:56:14.159Z [1] [ERROR] [outbound] Ongoing connection failed to 212.27.48.7:25 : Error: 140248129664832:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s23_clnt.c:802:
...
2018-06-02T15:03:46.335Z [1] [INFO] [outbound] Temp failing 1527951373843_1527951825107_3_611_5hphaG_12_<myhostname> for 512 seconds: Tried all MXs
```

Part of the mail header (my-domain.com is just here to replace my real domain name) : 
```
by <my-domain.com> (Haraka) with ESMTPSA id 9E5E0933-CDEE-4508-976C-0CD3FB90D276.1
	envelope-from <postmaster@<mydomain.com>> (authenticated bits=0)
	(version=TLSv1/SSLv3 cipher=ECDHE-RSA-AES256-GCM-SHA384 verify=FAIL);
```

**Comment by msimerson** [comment] 2018-06-02 20:36
> 2018-06-02T14:56:14.159Z [1] [ERROR] [outbound] Ongoing connection failed to 212.27.48.7:25 : Error: 140248129664832:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s23_clnt.c:802

That's telling you that the attempt to set up a secure connection (STARTTLS) setup with the next MX failed. My first guess is that it's caused by the remote (212.27.48.7) having a recent secure version of OpenSSL and your host running an older distro that hasn't been updated with the latest OpenSSL. Or perhaps your version of node.js is out of date and is thus running a deprecated version of openssl.

**Comment by vincowl** [comment] 2018-06-03 19:44
Thanks for this quick answer
Here are the versions that can be found in my poste.io installation

- node : 8.11.2
- openssl used by node : 1.0.2o
- openssl installed on host : 1.1.0f

I absolutely have no idea how to test which openssl version is used while trying to send an email... While Poste.io does not provide its dockerfile (I didn't found it), I absolutely don't know how node is installed. On top of that, the included npm version is broken, so there is no way to update the openssl lib.

**Comment by analogic** [comment] 2018-06-04 09:11
Node 10.x solve this issue. It seems very similar as https://github.com/nodejs/node/issues/16196 (nodejs has ecdhCurve set to prime256v1) but I was unable to fix this by setting tls.ini `[outbound] ecdhCurve auto` at node 8.

Another thing is that free.fr behaves somewhat strange by closing tls connections even if I test sending email with `openssl s_client -starttls smtp -crlf -connect 212.27.48.7:25` - might be graylisting or whatever because some attempts goes through ok...

**Comment by analogic** [comment] 2018-06-04 12:28
Hmm another instance with node 10.3 (of. package) and outbound can't initiate connection after startssl again. `s_client` is still working. There is something weird happening in node

**Comment by analogic** [comment] 2018-06-04 15:02
Finaly! Node 10.3 solves this problem (other problem was that target cipher was not at cipherlist)

**Comment by analogic** [comment] 2018-06-05 07:06
You can close this one @msimerson. At the end it was all about missing ciphers and my confusion about [main] ciphers+[outbound] ciphers (not working) vs [inbound]+[outbound] (working)

**Closed** 2018-06-05 14:07 UTC
