### ISSUE TITLE
Multiple domains IP

### ISSUE THREAD

**Issue by Happyrain67** [haraka/Haraka#2836] opened 2020-09-14 13:01 UTC
Hello,

I have installed and configured successfully Haraka.

I need your help to configure it to work properly with multiples domains :

I want to output an email from a great address IP sender.

www.domainA.com send email from IP-a (like 45.12.23.22)
www.domainB.com send email from IP-b (like 12.78.66.99)

I can write my plugin, but I don't know what hook is used for this.
if I'm right, the variable hmail.todo.outbound_ip is an IP for the MX recipient.

How can I change the IP of the sender ?

Thanks a lot,

**Comment by msimerson** [comment] 2020-09-14 17:11
duplicate of #442

**Closed by msimerson** 2020-09-14 17:11 UTC
