### ISSUE TITLE
Adding spam complaints, abuse and list-unsubscribe, click tracking

### ISSUE THREAD

**Issue by ravivgolov** [haraka/Haraka#3380] opened 2024-07-02 06:00 UTC
Hello,

I have already searched, but I haven't found any way to integrate incoming email tracking, spam complaints, abuse reports, list-unsubscribe requests, and click tracking for security. Since Haraka is mainly good at spam filtering, these additional features can enhance the spam filter's effectiveness by over 300%.

If there is any solution, I would pay to integrate this into Haraka,

Thank you.

**Comment by piboistudios** [comment] 2024-08-03 15:34
Haraka itself is just an SMTP server, so most of the things here mentioned are out of scope, except list unsubscribe, if I'm not mistaken. Click-tracking for sent e-mails will always be difficult because most vendors will remove any external references from the email and replace them with cached versions, so when the recipient receives the email and hits what would have been a reference to a click-tracking URL, it will actually be a cached version stored on the recipient mail server side, and thus won't notify you when the link is actually clicked, only when the mail is actually processed (which may or may not have anything to do with interaction on the recipient side).

**Comment by baudehlo** [comment] 2024-08-03 15:58
I once built something like this using the body filter plugin technology
(that's what I wrote it for originally). Basically it would remember the
email contents and then add a link to mark it as spam. It didn't work that
well, but I didn't spend a lot of time on it.

The problem is this sort of thing needs to be part of the email client, not
the SMTP server.

In short: Non-trivial, you can make it work, good luck.

**Closed** 2024-10-30 20:23 UTC
Labels: Feature Request
