### ISSUE TITLE
Haraka needs an option of storing what exactly is received without stamping additional headers

### ISSUE THREAD

**Issue by sathishvenkataraman** [haraka/Haraka#2767] opened 2020-02-29 13:31 UTC
### system info

Please report your OS, Node version, and Haraka version by running this shell script on your Haraka server and replacing this section with the output.

Haraka | Haraka.js — Version: 2.8.23
 --- | :---
Node | v10.17.0
OS | CYGWIN_NT-10.0 5570-7VTRPF2 2.11.2(0.329/5/3) 2018-11-08 14:34 x86_64 Cygwin
openssl | OpenSSL 1.0.2p  14 Aug 2018

### Expected behavior
Haraka to had some option of storing the received EML as-is without stamping additonal headers.  I used postfix earlier and it had that option
### Observed behavior
Today there is no way of storing eml without stamping addtional headers, especially the following:
1) Received: 
2) Original-Authentication-Results: xxxx.yyyy.com;

### Steps to reproduce
Send any email and you willl see these headers stamped

**Comment by msimerson** [comment] 2020-02-29 14:45
Document your request. Provide URLs to the postfix feature. How exactly do you want to store the original email?

**Comment by sathishvenkataraman** [comment] 2020-02-29 16:19
@msimerson i couldnt find a document on postfix, but based on my few years experience with postfix, it does not stamp these headers by default configuration.  There are certain non-routing features where we may not require these headers to be stamped, hence this request of making "not stamping" optional controlled by a config property.  The received email is stored as a static document (.eml) file and not for further routing.

**Comment by msimerson** [comment] 2020-04-11 06:29
duplicate of #2766. See comments there.

**Closed by msimerson** 2020-04-11 06:29 UTC
Labels: Feature Request
