### ISSUE TITLE
Rewrite attachment parsing code

### ISSUE THREAD

**Issue by celesteking** [haraka/Haraka#1715] opened 2016-11-14 12:59 UTC
Attachment parsing/handling code is crap.

The code/flow is impossible to understand and documentation is lacking, `transaction.attachment_hooks` is a shame, it doesn't follow standard haraka hook style when you have to call next() cb in order to proceed further. More than that, it doesn't reflect it's name, the hook itself is called when whole attachment is parsed, and recommended usage ( using 4th argument, AttachmentStream to do the work ) defeats its purpose. The stream is emitted when whole attachment is already there, not when haraka started parsing it and stream emits stuff when that stuff is received/(parsed live) by haraka core.

Making next available would allow get rid of crazy hacks I/we have to implement in order to pause processing before the dot response.

**Comment by celesteking** [comment] 2016-11-14 13:06
related to #1323 , probably.

**Comment by celesteking** [comment] 2016-11-14 13:28
Now I take my words back re: whole attachment being buffered. It seems I was testing on atts < mailparser.bufsize . Just tried 1MB , it indeed sent it down the attstream progressively in chunks.

Still, my complaint applies - code is hard to understand and no mention of this specifics in docs.

**Comment by msimerson** [comment] 2017-07-29 00:01
Closing as duplicate of #1323.

**Closed by msimerson** 2017-07-29 00:01 UTC
