### ISSUE TITLE
Bounce mail Auto Connection Down  generate temporary fie in multiple mail send 

### ISSUE THREAD

**Issue by rc111** [haraka/Haraka#2285] opened 2017-11-02 12:36 UTC
### system info

Haraka | Haraka.js — Version: 2.8.16
 --- | :--- 
Node | v7.9.0
OS | Linux vps.getitcharge.tech 2.6.32-042stab123.2 #1 SMP Mon Apr 17 17:27:00 MSK 2017 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.1e-fips 11 Feb 2013

### Expected behavior
All Emails Are send  properly .

### Observed behavior
Haraka bounce the mails and generate the temporary file of the mail clients, with it also generate the statement that mails are Double Bounced beacuse no such file is found in /etc/haraka/queue/filename.tech 
It also stuck the system to auto shutdown  the service .
it is used the retrieve of mail again and again , how to set the service for single bounce .

**Comment by baudehlo** [comment] 2017-11-02 13:21
Can you be a little more clear on the problem?

**Comment by rccess** [comment] 2017-11-02 14:06
Let me explain you !
We are supposed to check what maximum bounce emails haraka can catch up ! 
Note : we are not a spammer , we need to just check it out for testing purpose 

Our List have a lot of bounce addresses and the concern is that queue is getting bounce emails in queue and get stuck due to no delivery. and haraka process getting shutdown

We are looking for the following options
1. Skip Bounces are after one time sending 
2. or Create separate queue for bounce so normal emails don't get stuck
3. create separate queue according to user (which is taking from connection.notes.auth_user)


Please advise 

Thanks

**Comment by rc111** [comment] 2017-11-06 10:53
Here is the main Error 

[CRIT] [-] [core] Error: Callback was already called.
[CRIT] [-] [core]     at /usr/lib/node_modules/Haraka/node_modules/async/dist/async.js:903:32
[CRIT] [-] [core]     at HMailItem.hmail.next_cb (/usr/lib/node_modules/Haraka/outbound/queue.js:40:9)
[CRIT] [-] [core]     at HMailItem.events.EventEmitter.HMailItem.discard (/usr/lib/node_modules/Haraka/outbound/hmail.js:1221:14)
[CRIT] [-] [core]     at /usr/lib/node_modules/Haraka/outbound/hmail.js:1183:18
[CRIT] [-] [core]     at async.forEachSeries (/usr/lib/node_modules/Haraka/outbound/index.js:272:17)
[CRIT] [-] [core]     at /usr/lib/node_modules/Haraka/node_modules/async/dist/async.js:421:16
[CRIT] [-] [core]     at replenish (/usr/lib/node_modules/Haraka/node_modules/async/dist/async.js:941:25)
[CRIT] [-] [core]     at iterateeCallback (/usr/lib/node_modules/Haraka/node_modules/async/dist/async.js:931:17)
[CRIT] [-] [core]     at /usr/lib/node_modules/Haraka/node_modules/async/dist/async.js:906:16
[CRIT] [-] [core]     at /usr/lib/node_modules/Haraka/outbound/index.js:297:17
[NOTICE] [-] [core] Shutting down

**Comment by baudehlo** [comment] 2017-11-06 14:14
This is a duplicate of #1954

**Closed** 2017-11-06 16:03 UTC

**Comment by rc111** [comment] 2017-11-07 06:47
I'm using the your tracing code , it shows error

[ERROR] [3C67CF0C-579C-4D7B-BD27-B0FB2E7F6D36.1.1] [outbound] Double bounce: Error populating bounce message: Error: ENOENT: no such file or directory, open '/etc/haraka/queue/1510036782258_1510036981438_2_4929_Mp1Pl0_1794_op.example.com'
Previous call: Error
at HMailItem.hmail.next_cb (/usr/lib/node_modules/Haraka/outbound/queue.js:45:15)
at HMailItem.events.EventEmitter.HMailItem.discard (/usr/lib/node_modules/Haraka/outbound/hmail.js:1221:14)
at finish_processing_mail (/usr/lib/node_modules/Haraka/outbound/hmail.js:617:18)
at pluggableStream. (/usr/lib/node_modules/Haraka/outbound/hmail.js:830:33)
at emitOne (events.js:116:13)
at pluggableStream.emit (events.js:211:7)
at pluggableStream.socket.process_data (/usr/lib/node_modules/Haraka/line_socket.js:24:20)
at pluggableStream. (/usr/lib/node_modules/Haraka/line_socket.js:35:48)
at emitOne (events.js:116:13)
at pluggableStream.emit (events.js:211:7)
[CRIT] [-] [core] Error: Callback was already called.
[CRIT] [-] [core] at /usr/lib/node_modules/Haraka/node_modules/async/dist/async.js:903:32
[CRIT] [-] [core] at HMailItem.hmail.next_cb (/usr/lib/node_modules/Haraka/outbound/queue.js:46:9)
[CRIT] [-] [core] at HMailItem.events.EventEmitter.HMailItem.double_bounce (/usr/lib/node_modules/Haraka/outbound/hmail.js:1191:10)
[CRIT] [-] [core] at /usr/lib/node_modules/Haraka/outbound/hmail.js:1175:25
[CRIT] [-] [core] at ReadStream. (/usr/lib/node_modules/Haraka/outbound/hmail.js:943:13)
[CRIT] [-] [core] at emitOne (events.js:116:13)
[CRIT] [-] [core] at ReadStream.emit (events.js:211:7)
[CRIT] [-] [core] at fs.js:1987:12
[CRIT] [-] [core] at FSReqWrap.oncomplete (fs.js:135:15)
[NOTICE] [-] [core] Shutting down

**Comment by rc111** [comment] 2017-11-07 06:49
The code is , in outbound/queue.js
var delivery_queue = exports.delivery_queue = async.queue(function (hmail,
cb) {
    in_progress++;
    var prev_call;
    hmail.next_cb = function () {
        if (prev_call) {
            console.error("Previous call: ", prev_call);
        }
        in_progress--;
        prev_call = (new Error()).stack;
        cb();
    };
    hmail.send();
}, cfg.concurrency_max);
